### ISSUE TITLE
Abort when exporting data of table containing GTT

### ISSUE THREAD

**Issue by gh-k-murata** [darold/ora2pg#1492] opened 2022-09-06 02:33 UTC
hello.
In Ora2Pg v23.1, if you set the TYPE directive to INSERT or COPY and the FILE_PER_TABLE directive to 1 and try to export the data of a table containing GLOBAL TEMPORARY TABLE (GTT), the process will be aborted when exporting the GTT.

Added in commit ccf76f1, setting the EXPORT_GTT directive from 0 to 1 does not throw an error, but the INSERT and COPY SQL scripts include the GTT.
I would like to remove the GTT data addition command when importing to PostgreSQL because there is a problem.

Exporting data with GTT seems pointless, so when exporting data from a table with INSERT and COPY, is it possible to exclude GTT regardless of directive settings?

**Comment by darold** [comment] 2022-09-06 09:15
Commit 0e1bc39 might fix this issue, thanks.

**Comment by gh-k-murata** [comment] 2022-09-07 04:30
Thank you for quick response.
When I try with commit 0e1bc39 it no longer aborts, but the non-GTT table processed after the GTT is output with the file name tmp_GTT_TABLE_NAME_output.sql .
It seems that once GTT processing is entered, a temporary file for GTT output continues to be used until data for non-GTT tables is output.
In addition, script file names for GTT are listed in output.sql. 
Below is the information when Ora2Pg is executed. please check again.

Ora2Pg is running in the following environment:

OS: Windows10 Pro 64bit 21H2
Perl: Strawberry Perl for Windows 5.32.1.1

Console and file output for GTT and non-GTT output when running Ora2Pg (table names and query commands edited):

Console output:

[2022-09-07 11:52:03] Exporting data of table GTT_TABLE1...
[2022-09-07 11:52:03] Dumping data from GTT_TABLE1 to file: tmp_GTT_TABLE1_output.sql
[2022-09-07 11:52:03] Table GTT_TABLE1 has no column defined, skipping...
[2022-09-07 11:52:03] Renaming temporary file C:\ora2pg\copy_data/tmp_GTT_TABLE1_output.sql into C:\ora2pg\copy_data/GTT_TABLE1_output.sql
[2022-09-07 11:52:03] Exporting data of table GTT_TABLE2...
[2022-09-07 11:52:03] Dumping data from GTT_TABLE2 to file: tmp_GTT_TABLE2_output.sql
[2022-09-07 11:52:03] Table GTT_TABLE2 has no column defined, skipping...
[2022-09-07 11:52:04] Exporting data of table TARGET_TABLE1...
[2022-09-07 11:52:04] Dumping data from TARGET_TABLE1 to file: tmp_TARGET_TABLE1_output.sql
[2022-09-07 11:52:04] Looking how to retrieve data from TARGET_TABLE1...
[2022-09-07 11:52:04] DEGUG: Query sent to Oracle: SELECT "TARGET_TABLE1_COLUMN1"... FROM "SCHEMA"."TARGET_TABLE1" a
[2022-09-07 11:52:04] Fetching all data from TARGET_TABLE1 tuples...
[2022-09-07 11:52:04] DEBUG: number of rows 6 extracted from table TARGET_TABLE1
[2022-09-07 11:52:04] DEBUG: Formatting bulk of 2000 data (real: 6 rows) for PostgreSQL.
[2022-09-07 11:52:04] DEBUG: Creating output for 2000 tuples
[2022-09-07 11:52:04] Dumping data from TARGET_TABLE1 to file: tmp_TARGET_TABLE1_output.sql
[2022-09-07 11:52:04] Extracted records from table TARGET_TABLE1: total_records = 6 (avg: 6 recs/sec)
[2022-09-07 11:52:04] Extracted records from table TARGET_TABLE1: total_records = 6 (avg: 6 recs/sec)
[2022-09-07 11:52:05] Exporting data of table TARGET_TABLE2...
[2022-09-07 11:52:05] Dumping data from TARGET_TABLE2 to file: tmp_TARGET_TABLE2_output.sql
[2022-09-07 11:52:05] Looking how to retrieve data from TARGET_TABLE2...
[2022-09-07 11:52:05] DEGUG: Query sent to Oracle: SELECT "TARGET_TABLE2_COLUMN1"... FROM "SCHEMA"."TARGET_TABLE2" a
[2022-09-07 11:52:05] Fetching all data from TARGET_TABLE2 tuples...
[2022-09-07 11:52:05] DEBUG: number of rows 1 extracted from table TARGET_TABLE2
[2022-09-07 11:52:05] DEBUG: Formatting bulk of 2000 data (real: 1 rows) for PostgreSQL.
[2022-09-07 11:52:05] DEBUG: Creating output for 2000 tuples
[2022-09-07 11:52:05] Dumping data from TARGET_TABLE2 to file: tmp_TARGET_TABLE2_output.sql
[2022-09-07 11:52:05] Extracted records from table TARGET_TABLE2: total_records = 1 (avg: 1 recs/sec)
[2022-09-07 11:52:05] Renaming temporary file C:\ora2pg\copy_data/tmp_TARGET_TABLE2_output.sql into C:\ora2pg\copy_data/TARGET_TABLE2_output.sql

Output file 1: tmp_GTT_TABLE1_output.sql

SET client_encoding TO 'UTF8';
SET synchronous_commit TO off;

SET client_encoding TO 'UTF8';
SET synchronous_commit TO off;

SET client_encoding TO 'UTF8';
SET synchronous_commit TO off;


COPY target_table1 (target_table1_column1...) FROM STDIN;
target_table1_row_values...
\.


Output file 2: TARGET_TABLE2_output.sql

SET client_encoding TO 'UTF8';
SET synchronous_commit TO off;


COPY target_table2 (target_table2_column1...) FROM STDIN;
target_table2_row_values...
\.


Output file 3: output.sql

BEGIN;

\i 'C:\ora2pg\copy_data/GTT_TABLE1_output.sql'
\i 'C:\ora2pg\copy_data/GTT_TABLE2_output.sql'
\i 'C:\ora2pg\copy_data/TARGET_TABLE1_output.sql'
\i 'C:\ora2pg\copy_data/TARGET_TABLE2_output.sql'

COMMIT;

**Comment by darold** [comment] 2022-09-09 09:43
hum, maybe export_gtt was disabled too early, new commit b7f369e do it later.

Also note that if your data directory is not empty ora2pg will not remove old files so maybe there is old file that should be removed. Unfortunately I can not test it for the moment but I will do this weekend.

**Comment by darold** [comment] 2022-09-22 16:30
Closing, not reproducible whatever is the value of EXPORT_GTT, for me it is fixed.

**Closed by darold** 2022-09-22 16:30 UTC

**Comment by gh-k-murata** [comment] 2022-09-26 14:18
I'm sorry. It would have been better to post the previous output result as it is without editing.

It outputted fine for a small schema with 3 regular tables and 2 global temp tables I created for testing.

However, the schema I actually want to output has 800 regular tables, 7 foreign tables, and 133 global temporary tables.
I want the 800 regular tables in this schema to be output, but there are also 98 global temporary tables in output.sql.

I acquired ora2pg as of 2022/09/26, changed various settings and tested it, but the situation did not improve.
Attached is the output result of the above schema. Please check it if you don't mind.
I deleted the data part because the file size is large.
[ora2pg.zip](https://github.com/darold/ora2pg/files/9646993/ora2pg.zip)

**Comment by darold** [comment] 2022-09-26 16:43
There is a problem here that I can not investigate from ora2g log. Can you send me an expdp export of the Oracle database to my private email gilles AT darold DOT net so that I will be able to find why you have such export. Note that I have removed your zip ora2pg export file from your previous note, better is to send such file to my private address or ora2pg AT darold DOT net, this is the same.

**Comment by darold** [comment] 2022-09-26 16:43
I forgot to say that I only need the DDL part, no data in the expdp export.

**Comment by gh-k-murata** [comment] 2022-09-27 07:17
Thank you for your answer and for deleting the zip file.

As you informed me, I only exported the data structure with the desired schema.
However, the dump file size is 13.3 MB after zip compression.

My mailer doesn't allow sending this size, so I sent it in two batches of 6.6MB each.
If you did not receive it there, please contact us.

I also tried deleting multiple types of objects and exporting the data with Ora2pg.
When I removed all the constraints, the previously reported behavior did not occur and the output was fine.
Report the constraint data as it may be related to the behavior of the problem.

**Comment by darold** [comment] 2022-10-05 16:14
Sorry for the response delay. I was able to test your expdp export and I must say that I'm not able to reproduce the issue. I'm running ora2pg with latest development code on a linux system so I recommend you to do the same, it is possible that there is an issue on Windows but I will not be able to fix it.

**Comment by gh-k-murata** [comment] 2022-10-11 11:59
Thanks for retesting using the expdp dump file.
I also checked in a Linux environment.
Unfortunately, Ora2Pg is not working as intended even on Linux.

The previously reported issue of the "output.sql" file having an additional filename for the GTT table has been resolved for both Windows and Linux.

Also, the previously reported "tmp_GTT_TABLE1_output.sql" file does not remain on Linux.
However, the correct file name "TARGET_TABLE1_output.sql" is not output, but "GTT_TABLE1_output.sql" is output.
The only difference between Windows and Linux is whether the "tmp_GTT_TABLE1_output.sql" file is renamed to "GTT_TABLE1_output.sql" or not.

I tested by adding debug output to the temporary file open/close locations in "lib/Ora2Pg.pm".
As a result of the test, with non-GTT tables, the subroutine "_extract_data" closes the temporary file and releases the file handle "$self->{cfhout}".
However, in the GTT table, this closing process is not executed, the temporary file remains open, and the file handle "$self->{cfhout}" is not released.
Therefore, in the non-GTT table processed immediately after the GTT table, "$self->{cfhout}" is still defined.
Then, the condition "if (!defined $self->{cfhout})" in the subroutine "_export_table_data" becomes "false" and the temporary file opening is skipped.

Is this behavior affecting this issue?

Translated with www.DeepL.com/Translator (free version)

**Comment by gh-k-murata** [comment] 2022-10-18 15:47
The following is a new situation that has been discovered through verification.

When "TYPE" is "INSERT" or "COPY", the subroutine "_get_sql_statements" in lib/Ora2Pg.pm retrieves the target table names from the hash "$self->{tables}".
Initially "$self->{tables}" has no GTT table names, but when the subroutine "_partitions" is executed in the following code, the GTT table names are added to the hash.

    # Get partition information
    $self->_partitions() if (! $self->{disable_partition});

As previously reported, the 'INSERT' or 'COPY' process does not handle GTT table names correctly if they are passed to it.
I tested by changing "DISABLE_PARTITION" from "0" to "1" so that the above code would not be executed.
As a result, the expected results are output in both Windows and Linux environments.

Most GTT tables have either primary or unique key constraints.
I have previously reported that if I remove all constraints, it works fine.
Is the problem caused by the "DISABLE_PARTITION" being "0" and the GTT tables having primary key constraints?

I do not currently use partition tables in Oracle, so I set "DISABLE_PARTITION" to "1" to avoid the problem.

I used Ora2Pg Version 23.2 for testing.
