### ISSUE TITLE
index names with _i prefix that don't exist in the case of foreign key constraints

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1304] opened 2021-11-30 17:18 UTC
(using ora2pg v23.0)

In the generated schema/tables/table.sql I see code like the following:

    `ALTER TABLE schemaname.tablename ADD CONSTRAINT constraintname_fk FOREIGN KEY (efo_id) REFERENCES schemaname.someothertablename(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;`

In the generated schema/tablespaces/tablespace.sql the index is named differently (i.e. suffixed with "_i"):

    `ALTER INDEX schemaname.constraintname_fk_i SET TABLESPACE sometablespace; `

This causes the `import_all.sh` script to fail when trying to load tablespace.sql with:

    psql:./schema/tablespaces/tablespace.sql:12: ERROR:  relation "schemaname.constraintname_fk_i" does not exist
    ERROR: an error occurs when importing file ./schema/tablespaces/tablespace.sql.

AFAICS this problem only occurs in indexes for foreign key constraints, i.e. not for primary keys or unique constraints.
In the ora.conf file I have:

    INDEXES_SUFFIX          _idx 
    INDEXES_RENAMING        1

**Comment by darold** [comment] 2021-11-30 18:25
Well there is a limitation here. The problem is that we just have the index name not the table which prevent looking at the indexes definition which are stored by table name. This is probably impossible to solve, Oracle allow the same index name to be used for several tables which prevent storage by index name to retrieve the columns names to rename the index. I would say don't enable USE_TABLESPACE if you want to rename indexes. It won't be fixed.

**Closed** 2021-12-05 04:09 UTC
