### ISSUE TITLE
Out of Memory when running show_report

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#1096] opened 2021-03-04 09:01 UTC
![image](https://user-images.githubusercontent.com/64629858/109938441-073a6a80-7cf6-11eb-936a-49b18275fe8a.png)

System memory reaches upto 98% and the command throws out of memory exception. Pls. help to resolve this. its urgent.

**Comment by deepakp555** [comment] 2021-03-16 09:37
I am struggling with out of memory issue when run the show_report command. This command works well for other schema in the same database server, but for 2 schemas this runs out of memory as indicated in screen shot. if anyone have any lead to resolve such issue it will be great help.

**Comment by darold** [comment] 2021-03-16 17:24
This is not a problem I can solve without being able to reproduce it. I recommend you to use Ora2Pg on Linux to see if the problem is not related to Windows port.

**Comment by deepakp555** [comment] 2021-03-16 17:31
So basically you saying that , to run show_report command for rest 2 schema i need to run the Ora2Pg tool on linux machine instead windows machine.The OOM issue is due to windows machine.?

**Comment by darold** [comment] 2021-03-16 17:52
I don't say it is due the Windows OS itself, but it can be related either to Perl on Windows or probably more to an Ora2Pg. On my side even on Windows I'm not able to reproduce the problem but every Oracle database is different and my test database can not generate such problem, even with huge number of objects. What I suggest is to use Linux because Ora2Pg is developed and tested on Linux. If you were able to do that we could eliminate the possibility that the problem is related to an execution on Windows Os.

I have suspected some kind of infinite loop on VIEW export because the OOM occurs at this stage, but I can't find it without a case to reproduce. If I remember well I have fixed one several weeks ago so if you don't have an up to date Ora2Pg please use latest development code.

Globally with such report where I have no access to the Oracle objects definition to try to reproduce the issue, I'm not of a great help.

**Comment by deepakp555** [comment] 2021-03-17 05:54
Thanks for such clarification and early reply.
I woul clarify some points. I have  tried to run the show_report command from ora2pg v20.0 and 21.0 both but it was no luck and have the same issue. Also from "TYPE" parameter of config file i have removed the "view" and "mview" but it still runs for view objects.
Like to ask is there any way to remove the any specific object type from scanning list so that report can be contonued. Thanks

**Comment by darold** [comment] 2021-03-17 06:57
Download latest development code, comment line 15994 of file lib/Ora2pg.pm then install the new code. This line must looks like:
```
#                %view_infos = $self->_get_views() if ($self->{estimate_cost});
```
A comment starts with a # character in Perl.

This will force Ora2Pg to not look at views.

**Comment by deepakp555** [comment] 2021-03-17 08:31
It worked for me. Thanks for the resolution. I have one more small query. There are DB links available in my database which are identified by any one of the following queries.
select * from DBA_DB_LINKS;
select * from ALL_DB_LINKS;
select * from USER_DB_LINKS;

But in ora2pg  show_report  command it always results  0. can you please check.

**Comment by darold** [comment] 2021-03-21 21:07
If SHOW_REPORT doesn't reports the DBLINK this is probably because they are not in the schema scanned ,this is the only filter used on ALL_DB_LINKS.

**Closed by darold** 2021-03-21 21:07 UTC
