### ISSUE TITLE
Calling functions with same name declared in several packages

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#399] opened 2017-05-05 11:04 UTC
Initial title was "Unwanted comma when replacing OUT parameters" but this symptom will be another issue if not yet solved.

My Oracle proc is:
  PROCEDURE GET_NB_SUB_ELEMS( v_nb_spaces OUT BINARY_INTEGER
                            , v_nb_us OUT BINARY_INTEGER
                            , p_subscription_id T_SUBSCRIPTION.subscription_id%TYPE
                            , p_date_begin T_SUBSCRIPTION.date_validity_end%TYPE default null
                            , p_date_end T_SUBSCRIPTION.date_validity_end%TYPE default null
                            , p_type_of_target T_TYPE_OF_TARGET.type_of_target_id%TYPE default null
                            );

The translated call is:
SELECT * FROM pck_gcl.get_nb_sub_elems(p_subscription_id, v_date_start, v_date_end , ) INTO  v_quantity, v_new_max_subscriber;

**Comment by okbob** [comment] 2017-05-05 11:34
It is same issue like #354

**Comment by edelanoe** [comment] 2017-05-05 11:35
Extra info: the issue does not appear with this proc, with OUT params on the same line:
PROCEDURE GET_NB_TICKETS_VEHICLES( v_nb_spaces OUT BINARY_INTEGER, v_nb_tickets OUT BINARY_INTEGER, v_nb_vehicles OUT BINARY_INTEGER
                            , p_subscription_id T_SUBSCRIPTION.subscription_id%TYPE
                            , p_date_begin T_SUBSCRIPTION.date_validity_end%TYPE default null
                            , p_date_end T_SUBSCRIPTION.date_validity_end%TYPE default null
                            );
A call is 
    GET_NB_TICKETS_VEHICLES( v_quantity , v_new_max_ticket_subscription , v_new_max_vehicle , p_subscription_id , v_date_start , v_date_end );

Translated (before resolution of issue #398):
    SELECT * FROM .get_nb_tickets_vehicles(p_subscription_id, v_date_start, v_date_end ) INTO  v_quantity, v_new_max_ticket_subscription, v_new_max_vehicle;

**Comment by edelanoe** [comment] 2017-05-05 11:41
Ok Pavel(okbob), I will close this issue once all information in this one has been acknowledged.
Cheers

**Comment by edelanoe** [comment] 2017-05-05 11:50
More information on OUT parameter translations. I put it here because I suspect it has the same cause. Ask me to open a new issue if needed.
The calls of the following Oracle proc are translated a surprising way:
  PROCEDURE UPD_NB_OF_PARK_SPACES( p_subscription_id IN T_SUBSCRIPTION.subscription_id%TYPE
                                  , p_nb_of_park_space IN T_SUBSCRIPTION.max_total_park_spaces%TYPE default null
                                  , p_date_start T_SUBSCRIPTION.date_validity_begin%TYPE default null
                                  , p_date_end T_SUBSCRIPTION.date_validity_end%TYPE default null
                                  -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé pour assurer les annulations des paniers de création
                                  , p_force NUMBER default 0 -- 1 <=> toujours accepter le transfert même s'il est payant
                                  , v_result OUT NUMBER );
Original call:
UPD_NB_OF_PARK_SPACES( p_subscription_id => p_subscription_id_to
                            , p_nb_of_park_space => null
                            , p_date_start => p_date_start
                            , p_date_end => p_date_end
                            , p_force => p_force      -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé (annulations des paniers de création, scissions d'intervalles)
                            , v_result => v_result );

Translated call (before solution of issue #398):
v_result => v_result  := .upd_nb_of_park_spaces( p_subscription_id => p_subscription_id_to, p_nb_of_park_space => null, p_date_start => p_date_start, p_date_end => p_date_end, p_force => p_force      -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé (annulations des paniers de création, scissions d'intervalles)
);

**Comment by edelanoe** [comment] 2017-05-05 12:23
Other kind of manifestation, where we miss the PERFORM too:

Oracle declaration:
  PROCEDURE TRANSFER_SUBSCRIBER(p_subscriber_id IN T_SUBSCRIBER.subscriber_id%TYPE
                              , p_subscription_id_to IN T_SUBSCRIBER.subscription_id_transfer%TYPE
                              , p_date_start T_SUBSCRIBER.date_validity_begin%TYPE default null
                              , p_date_end T_SUBSCRIBER.date_validity_end%TYPE default null
                              , p_reason_tr_subsr_id T_SUBSCRIBER.reason_tr_subsr_id%TYPE default null
                              -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé pour assurer les annulations des paniers de création
                              , p_force NUMBER default 0 -- 1 <=> toujours accepter le transfert même s'il est payant
                              , v_result OUT NUMBER -- 0 ou code erreur -20100 à -20199
                              ) IS

Translated declaration:
CREATE OR REPLACE FUNCTION pck_gcl.transfer_subscriber (p_subscriber_id T_SUBSCRIBER.subscriber_id%TYPE , p_subscription_id_to T_SUBSCRIBER.subscription_id_transfer%TYPE , v_result OUT numeric  -- 0 ou code erreur -20100 à -20199
 , p_date_start T_SUBSCRIBER.date_validity_begin%TYPE default null , p_date_end T_SUBSCRIBER.date_validity_end%TYPE default null , p_reason_tr_subsr_id T_SUBSCRIBER.reason_tr_subsr_id%TYPE default null                               -- Modif-2015-08-31-1 EDe: ajout d'un mode forcé pour assurer les annulations des paniers de création
 , p_force numeric default 0 -- 1 <=> toujours accepter le transfert même s'il est payant
 ) AS $body$
DECLARE


Oracle call:
          TRANSFER_SUBSCRIBER ( p_subscriber_id => R.subscriber_id
                              , p_subscription_id_to => R.subscription_id
                              , p_date_start => null
                              , p_date_end => null
                              , p_force => p_force
                              , v_result => v_result
                              );

Translated call (2017-04-14 ora2pg download):
      for R in ( [...a query...] ) loop
           := pck_gcl.transfer_subscriber( p_subscriber_id => R.subscriber_id
                              , p_subscription_id_to => R.subscription_id
                              , p_date_start => null
                              , p_date_end => null
                              , p_force => p_force
                              , v_result => v_result
                              );
      end loop;

Translated call (2017-05-05 09:00 ora2pg download):
      loop
           := .transfer_subscriber( p_subscriber_id => R.subscriber_id, p_subscription_id_to => R.subscription_id, p_date_start => null, p_date_end => null, p_force => p_force, v_result => v_result
                              );
      end loop;

Also tell me if this should be a different issue...
Rgds,
Eric

**Comment by darold** [comment] 2017-05-05 14:36
I don't think I have put any work on named parameter this is the first time I'm encountered this use. I will check that too.

**Comment by darold** [comment] 2017-05-05 15:17
Ok, I've been able to reproduce the issue with unwanted comma. I will try to fixed it know.

**Comment by darold** [comment] 2017-05-05 17:34
Last commit 38f5d91 might solves this issue, the problem was that function parameters was doubled with the PACKAGE and PACKAGE BODY definition when extracting sources.

**Comment by edelanoe** [comment] 2017-05-09 14:30
The translated call initially described still has the same error (see 1st comment of this issue).
The other examples are not corrected either. They seem to have a different cause, so I will create a new issue.

However, I have seen another issue that is quite similar to the initial one: some parameters are missing in the translated call.

Oracle: 
-- a function with 3 params and another with 1 param
                    vResFnc := SEB(v_header,v_STRMSG,v_MSG_SESSION_BEGIN_ID);
                    vResFnc := PCK_MSG_EXT.SEB(v_MSG_SESSION_BEGIN_ID);
ora2pg output:
                    vResFnc := pck_msg_ext.seb(v_header, v_STRMSG);
                    vResFnc :=  := pck_msg_ext.seb(v_MSG_SESSION_BEGIN_ID, );

Therefore, I let this issue open as an independent one.
Best regards,
Eric

**Comment by edelanoe** [comment] 2017-05-10 12:11
This issue looks very specific to some functions with OUT parameters, which, basically, should be re-engineered.
Should I keep this issue open ?

**Comment by darold** [comment] 2017-05-10 19:15
If you can send to my private email the PCK_MSG_EXT I could try to reproduce the issue but like that I'm not able to reproduce the issue.

**Comment by edelanoe** [comment] 2017-05-15 08:17
Sorry, I have just learned that a function with OUT parameter(s) is "not supposed" to have a return type.
I have also learned that Oracle's feature allowing functions with OUT params AND a separate return value is NOT PORTABLE to PLPgsql.
I perfer to close this issue and provide new elements in a new one.

**Comment by darold** [comment] 2017-05-15 08:43
Please keep it open, the problem describe here is related to functions with same name declared in several package. I was able to reproduce the issue with the code you've sent to me and I'm still studying a solution.

**Comment by edelanoe** [comment] 2017-05-15 08:52
I agree, but the issue should change title or it will become useless. It is already rather “unreadable”…
I have seen this change should be possible on GIT. Greenlight from you?

Besides, I still prepare another code dump for you, because I suspect more than the package name issue.

Best regards,
E.Delanoë

De : Darold [mailto:notifications@github.com]
Envoyé : lundi 15 mai 2017 10:44
À : darold/ora2pg
Cc : Delanoe Eric; State change
Objet : Re: [darold/ora2pg] Unwanted comma when replacing OUT parameters (#399)


Please keep it open, the problem describe here is related to functions with same name declared in several package. I was able to reproduce the issue with the code you've sent to me and I'm still studying a solution.

**Comment by darold** [comment] 2017-05-16 16:58
Commit 76b75d7 might solve this problem.

**Comment by edelanoe** [comment] 2017-05-17 12:53
Thanks for the updates.
Some procedures are now taken from the right package while they were not, but...
The OUT parameter is not used as a return value anymore and we get a bare procedure call, not a function call.
Before commits 76b75d7 and 567c542 : v_MSG_SESSION_END_ID := pck_msg_ext.see(v_header, v_STRMSG);
Before commits 76b75d7 and 567c542 : pck_msg.see(v_header,v_STRMSG,v_MSG_SESSION_END_ID);
(sorry I cannot sort-out what commit did what)

Note: the function signature itself is left as-is:
Oracle:
PROCEDURE SEE ( v_header IN GEASTRUCT.A_MSG_HEADER%ROWTYPE, v_STRMSG IN CLOB, v_MSG_SESSION_END_ID OUT T_MSG_SESSION_END.MSG_SESSION_END_ID%TYPE) is
ora2pg: 
CREATE OR REPLACE FUNCTION pck_msg.see ( v_header GEASTRUCT.A_MSG_HEADER, v_STRMSG text, v_MSG_SESSION_END_ID OUT T_MSG_SESSION_END.MSG_SESSION_END_ID%TYPE) AS

And in the rest of the functions from the same package, calls to unqualified "to_money" function generates a call to "pck_gpar.to_money" where we have a copy of this function (right, it should be killed...)

Rgds,
Eric

**Comment by darold** [comment] 2017-05-21 09:22
New commit a0492e0 fixes additional issue on this code translation.

**Comment by darold** [comment] 2017-05-21 17:35
And commit d30498e fixes the previous patch.

**Comment by edelanoe** [comment] 2017-06-15 14:39
Hello,

The issue with "OUT parameter not used as a return value" (my previous comment) is fixed, but the unqualified function calls are not yet all well translated: when translating "pck_msg" package, all calls to unqualified "to_money" function (local in pck_msg) generates a call to "pck_gpar.to_money" instead of "pck_msg.to_money" (we have a function named "to_money" in a different package called pck_gpar).
Couldn't there be a priority to the local functions of the package ?

Rgds,
Eric

**Comment by darold** [comment] 2017-06-15 22:14
Some kind of next difficulty level :-) I will have a look.

**Comment by darold** [comment] 2017-06-16 09:22
Commit 82e1c91 might force function defined in the current package to take precedence on same function defined in other package.

**Comment by edelanoe** [comment] 2017-06-16 16:48
Not yet... At least it broke elsewhere:
                  v_MSG_SESSION_BEGIN_ID := pck_msg_ext.seb(v_header, v_STRMSG);
                  vResFnc := pck_msg_ext.seb(v_MSG_SESSION_BEGIN_ID);
should be
                  v_MSG_SESSION_BEGIN_ID := seb(v_header, v_STRMSG);
                  vResFnc := pck_msg_ext.seb(v_MSG_SESSION_BEGIN_ID);
I will send you a full input PL/SQL...

**Comment by darold** [comment] 2017-06-16 20:40
Thanks again for the PL/SQL it is very helpful. Commit 39c117d might fix this issue.

**Comment by edelanoe** [comment] 2017-06-27 14:01
There is evident progress, but there is regression between 06/15 and (06/19 or 06/27) versions:

- In literals : 
I had:
return pck_bdd.app_raise_error(SQLSTATE, ''||SQLERRM||' in pck_msg.to_money('||coalesce(v_str,'')||')');

which became quite funny:
return pck_bdd.app_raise_error(SQLSTATE, ''||SQLERRM||' in pck_msg.pck_gpar.pck_msg.pck_gpar.pck_msg.pck_gpar.pck_msg.pck_gpar.to_money('||coalesce(v_str,'')||')');

- In pck_msg.update_zone_waiting_time
I had (correct): PERFORM pck_cpt.msg_maj_cpt();
Which became: PCK_CPT.MSG_MAJ_CPT();

- In pck_msg.dispatch: unwanted RECORD use with a IN parameter
I had:                  v_header := pck_msg.header(v_STRMSG);   -- the parameter is IN
Which became:  SELECT * FROM pck_msg.header(v_STRMSG) INTO STRICT _ora2pg_r; v_header := _ora2pg_r.v_header;

I had: v_MSG_SESSION_BEGIN_ID := pck_msg.seb(v_header, v_STRMSG);
Which became less "smart" although still right:
SELECT * FROM pck_msg.seb(v_header, v_STRMSG) INTO STRICT _ora2pg_r; v_MSG_SESSION_BEGIN_ID := _ora2pg_r.v_MSG_SESSION_BEGIN_ID;

The Oracle source code is the one you already have.

Thanks again,
Eric

**Comment by darold** [comment] 2017-06-27 16:30
> In pck_msg.dispatch: unwanted RECORD use with a IN parameter
> I had: v_header := pck_msg.header(v_STRMSG); -- the parameter is IN
> Which became: SELECT * FROM pck_msg.header(v_STRMSG) INTO STRICT _ora2pg_r; v_header := _ora2pg_r.v_header;

This is the new and right translation. The second parameter of pck_msg.header() is a composite type  OUT parameter : `FUNCTION pck_msg.header (v_STRMSG text, v_header OUT GEASTRUCT.A_MSG_HEADER)` so it must return the OUT value into a RECORD.

With the rewrite of `v_MSG_SESSION_BEGIN_ID := pck_msg.seb(v_header, v_STRMSG);` there is an issue, ora2pg must not take a parameter with table.column%TYPE as a composite type. Fixed with commit 8e26654.

Other issues are not reproduced in my environment.

**Closed** 2017-08-10 22:05 UTC
