### ISSUE TITLE
missing controll variables for FOR IN SELECT cycle

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#466] opened 2017-06-20 17:55 UTC
I found few another examples:
<pre>

  ------------REN PRESUNUTO 18.02.2016 BYLO NA KONCI KONTROL
  FOR qHL_DPHABC IN
    ( SELECT ID_HL_DPHABC, COUNT(*) AS POCET
         FROM (  SELECT MT.ID_HL_DPHABC , A2.ID_UCEDOKLAD
        FROM HL_DPHABC MT , HL_DPHUCE A1 , UCEPOHYB A2
        WHERE MT.ID_HL_DPHDAV = mID_HL_DPHDAV
          AND MT.KOD_ABC IN ('A1', 'A2','A4', 'B1','B2')
          AND MT.ID_HL_DPHABC = A1.ID_HL_DPHABC
          AND A1.ID_UCEPOHYB = A2.ID_UCEPOHYB
          GROUP BY MT.ID_HL_DPHABC ,A2.ID_UCEDOKLAD
          ORDER BY MT.ID_HL_DPHABC ,A2.ID_UCEDOKLAD  )
          GROUP BY ID_HL_DPHABC  )
   LOOP

     IF qHL_DPHABC.POCET > 1 THEN
       FOR qHL_DPHUCE IN
         ( SELECT DISTINCT A2.ID_HL_DPHABC
            FROM UCEPOHYB MT , HL_DPHUCE A1 , HL_DPHABC A2
            WHERE A1.ID_HL_DPHABC = qHL_DPHABC.ID_HL_DPHABC
              AND A1.ID_HL_DPHABC = A2.ID_HL_DPHABC
              AND MT.ID_UCEPOHYB = A1.ID_UCEPOHYB
              AND A2.ID_HL_DPHDAV = mID_HL_DPHDAV )
        LOOP
          UPDATE HL_DPHABC
            SET CHYBA_TEXT =  SUBSTR( CHYBA_TEXT || ' VICE DOKLADU IDES ' ,1,4000)
            WHERE ID_HL_DPHABC = qHL_DPHUCE.ID_HL_DPHABC;

        END LOOP;
     END IF;

   END LOOP;
</pre>
or
<pre>

    FOR qUcejedn IN
      ( SELECT * FROM V_LOGIN_UCEJEDN_VLAST
          WHERE ID_SSSLOGIN = mID_SSSLOGIN
            AND IDES_PRISTUP = 'A' )
    LOOP
      IF qUcejedn.ID_CISUJEDN IS NOT NULL THEN
        mDEL_ROLE := NULL;
        FOR qRole IN
          (  SELECT ID_ROLE , EDIT_PODMINKA , DEL_ROLE FROM SSSROLE WHERE KOD_ROLE = 'UCJEDNOTKA' )
        LOOP
          IF qRole.ID_ROLE IS NOT NULL THEN
             mID_Role := qRole.ID_ROLE ;
             mEdit_role := qRole.EDIT_PODMINKA ;
             mDEL_ROLE := qRole.DEL_ROLE;
          ELSE
            mChybaText := ' Nebyla nalezena role pro sdruzeni !!! ' ;
          END IF ;
          EXIT ;
        END LOOP ;
        IF mDEL_ROLE IS NULL THEN
          mDEL_ROLE := 'N';
        END IF;
        IF mDEL_ROLE = 'N' THEN
          IF qUcejedn.ID_APROVOZNA IS NOT NULL THEN
             SELECT ID_SKUP_CISEL INTO mID_SKUP_CISEL
               FROM UDRPROVO
               WHERE ID_APROVOZNA = qUcejedn.ID_APROVOZNA;
          END IF;
          INSERT INTO TEMP_LOGIN ( ID_TMPLOGIN , TYP ,ID_ROLE , ANAJMENO , ID_ASPRAVCE ,ID_SKUP_CISEL,ID_APROVOZNA, KOD_ROLE , EDIT_PODMINKA,
            jmeno_os, nazev_spravce, nazev_role, PREZENTACE_RAJONU , KOEFICIENT)
            VALUES ( mID_TMPLOGIN , 'U' , mID_Role , qUcejedn.NAZEV_FUNKCE  , qUcejedn.ID_ASPRAVCE ,mID_SKUP_CISEL,qUcejedn.ID_APROVOZNA, 'UCJEDNOTKA' , mEdit_role,
             qUcejedn.Najmeno,qUcejedn.Nazev_Cisujedn,'UCE pýˇstup', qUcejedn.Nazev_Cisujedn, 0);
        END IF;
        EXIT ;
      END IF ;
    END LOOP ;
</pre>
[TVORBA_KONT_HL_DPH.txt](https://github.com/darold/ora2pg/files/1089194/TVORBA_KONT_HL_DPH.txt)
[LOGIN_DO_APLIKACE.txt](https://github.com/darold/ora2pg/files/1089197/LOGIN_DO_APLIKACE.txt)

**Comment by darold** [comment] 2017-06-20 21:04
The origin of the problem is not in FOR IN SELECT cycle parsing but in a constant string that break the parser. I'm working on finding a solution.

**Comment by darold** [comment] 2017-06-21 10:59
Commit 87f83bc might fix this issue and the other related issues.

**Comment by okbob** [comment] 2017-06-21 18:14
Looks great! all issues in both procedures are fixed. Thank you very much

**Comment by okbob** [comment] 2017-06-21 18:25
Still I found one :( - but it is great progress 
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.VYU_TEPLO_PREPOCET_2016( mWhere IN VARCHAR2 , mTransakce IN CHAR , mLIDENT IN CLEOSOBY.LIDENT%TYPE , mTypPrepocet IN CHAR ) is
  mSqlVyrok VARCHAR2(4000);
  TYPE TqVyrok IS REF CURSOR;
  qVyrok TqVyrok;
  mID_VYROK VYROK.ID_VYROK%TYPE;
  mChyba VARCHAR2(4000);
  mID_VYROK_PARAMETR VYROK.ID_VYROK_PARAMETR%TYPE;
  mENAKLAD_NEW NUMBER;
  mPOCET_VYNAK  NUMBER;
  mID_VYNDEV VYNDEV.ID_VYNDEV%TYPE;
  mZAKLADNI_SLOZKA VYRZALPOD.ENAKLAD%TYPE;
  mKRIT_NEMER VYRZALPOD.KRIT_NEMER%TYPE;
  mMAX_KRIT_NEMER NUMBER;
  mPOCET_SPUS_METODY_TEP VYROK.POCET_SPUS_METODY_TEP%TYPE;
  mEnaklad_FM_bez_vyj NUMBER;
  mPl_FM_bez_vyj NUMBER;
  mPL_BYT_TEP NUMBER;
  mCastka_NaMetr NUMBER;
begin

  IF TRIM(mWhere) IS NOT NULL  THEN
    mSqlVyrok := ' SELECT ID_VYROK , ID_VYROK_PARAMETR ,ID_VYNDEV , POCET_SPUS_METODY_TEP  FROM V_VYROK MT WHERE TRIM(KOD_POLONAJ) = ''TEP'' AND  CH_PROC_TEPLO = ''A'' AND  ODVYU >= TO_DATE(''01.01.2016'' , ''DD.MM.YYYY'' ) AND ' || mWhere ;
  ELSE
    mSqlVyrok := ' SELECT ID_VYROK , ID_VYROK_PARAMETR ,ID_VYNDEV , POCET_SPUS_METODY_TEP  FROM V_VYROK  WHERE ID_VYROK = -1  ' ;
  END IF;


  IF mTransakce = 'A' THEN
    SET TRANSACTION READ WRITE ;

  END IF;

  ---raise_application_error( -20010, mSqlVyrok );

 OPEN qVyrok FOR mSqlVyrok ;
 LOOP
   FETCH qVyrok INTO mID_VYROK , mID_VYROK_PARAMETR , mID_VYNDEV , mPOCET_SPUS_METODY_TEP;
   EXIT WHEN qVyrok%NOTFOUND;

   DELETE FROM VYNAKBYT WHERE ID_VYROK = mID_VYROK_PARAMETR;

 END LOOP; 

  IF mTransakce = 'A' THEN
    COMMIT;
    SET TRANSACTION READ WRITE ;

  END IF;


 OPEN qVyrok FOR mSqlVyrok ;
 LOOP
   FETCH qVyrok INTO mID_VYROK , mID_VYROK_PARAMETR ,mID_VYNDEV , mPOCET_SPUS_METODY_TEP;
   EXIT WHEN qVyrok%NOTFOUND;

       mMAX_KRIT_NEMER := ( NVL(mPOCET_SPUS_METODY_TEP,0) + 1 );
       
       
       
        
       INSERT INTO RRRNAJUZA_ERR( AKCE , CHYBA )
         VALUES( 'FMCEL', mEnaklad_FM_bez_vyj || '---' || mPl_FM_bez_vyj  || '---' || mCastka_NaMetr );
               
       FOR qVYRZAL IN 
         ( SELECT ID_VYRZAL, ENAKLAD , PROCEN_PRUMER , ID_NAJVZTAH , ID_ASPRAVCE , ID_APROVOZNA , KRIT_NEMER , AKOD_PROSTOR , POCDEN
             FROM V_VYRZAL 
             WHERE ID_VYROK = mID_VYROK  AND ENAKLAD > 0  
               AND ( ( PROCEN_PRUMER <= 80 ) OR ( PROCEN_PRUMER >= 200 ) OR ( KRIT_NEMER IN ( '1' , '2' , '3' , '4' , '5' , '6' , '7' , '8' ,'9','P'  )) ) )
       LOOP
         
       

         SELECT sum(HODNOTA*POCDNU) / sum(POCDNU) INTO mPL_BYT_TEP
                         FROM V_VYRZALPOD_NAJPOLKRIT WHERE ID_VYRZAL = qVYRZAL.Id_Vyrzal; 
       
       
         mKRIT_NEMER := NULL;      
         IF NVL(qVYRZAL.Krit_Nemer,'NENI' ) NOT IN ( '1' , '2' , '3' , '4' , '5' , '6' , '7' , '8' ,'9','P'  ) THEN
           IF qVYRZAL.PROCEN_PRUMER <= 80 THEN 
             mENAKLAD_NEW := ( qVYRZAL.Enaklad / qVYRZAL.PROCEN_PRUMER  ) * 80;
             --mENAKLAD_NEW :=  mCastka_NaMetr * 0.8 * mPL_BYT_TEP;
             /*
             INSERT INTO RRRNAJUZA_ERR( AKCE , INFO , CHYBA )
               VALUES( 'BYT', qVYRZAL.AKOD_PROSTOR , mPL_BYT_TEP || ' 0.8 ' || mCastka_NaMetr );
             */  
           END IF;  

           IF qVYRZAL.PROCEN_PRUMER >= 200 THEN 
              mENAKLAD_NEW := ( qVYRZAL.Enaklad / qVYRZAL.PROCEN_PRUMER  ) * 200;
              /*
              mENAKLAD_NEW :=  mCastka_NaMetr * 2 * mPL_BYT_TEP;
              */
              /*  
              INSERT INTO RRRNAJUZA_ERR( AKCE , INFO , CHYBA )
                 VALUES( 'BYT', qVYRZAL.AKOD_PROSTOR ,  mPL_BYT_TEP || ' 2 ' || mCastka_NaMetr  );
              */   
         END IF;  

         ELSE
           mENAKLAD_NEW := qVYRZAL.Enaklad;
         END IF;  

           
          IF qVYRZAL.Krit_Nemer IN ( '1' , '2' , '3' , '4' , '5' , '6' , '7' , '8' ,'9' , 'P' ) THEN
               mKRIT_NEMER := qVYRZAL.Krit_Nemer;      
          ELSE
              mKRIT_NEMER :=  mMAX_KRIT_NEMER ;
          END IF;    
          
       
         BEGIN
           SELECT NVL(SUM(MT.ENAKLAD),0) INTO mZAKLADNI_SLOZKA
             FROM VYRZALPOD MT ,VYROKPOD A1,CISKRITYP A2
             WHERE MT.ID_VYRZAL = qVYRZAL.Id_Vyrzal
               AND MT.ID_VYROKPOD = A1.ID_VYROKPOD
               AND A1.ID_CISKRITYP = A2.ID_CISKRITYP  
               AND TRIM(A2.KOD_CISKRITYP) = 'ZAKLAD';
         EXCEPTION
           WHEN NO_DATA_FOUND THEN
             mZAKLADNI_SLOZKA := 0; 
         END;        
           
         BEGIN
           INSERT INTO VYNAKBYT ( ID_VYROK ,ID_NAJVZTAH , ZAKLAD , SPOTRE , ID_ASPRAVCE, ID_APROVOZNA ,  POZNAMKA , KRIT_NEMER )
              VALUES( mID_VYROK_PARAMETR ,qVYRZAL.ID_NAJVZTAH , mZAKLADNI_SLOZKA , ( mENAKLAD_NEW - mZAKLADNI_SLOZKA ) ,qVYRZAL.ID_ASPRAVCE, qVYRZAL.ID_APROVOZNA ,'PROCENT ' || qVYRZAL.Procen_Prumer || ' NAKLAD_PUV ' || qVYRZAL.ENAKLAD , mKRIT_NEMER );
         EXCEPTION
            WHEN OTHERS THEN
                mchyba := SQLERRM; 
                INSERT INTO RRRNAJUZA_ERR(AKCE , INFO , CHYBA)
                   VALUES( 'CH_NAJV' ,qVYRZAL.ID_NAJVZTAH ,mchyba );
                   SELECT COUNT(*) INTO mPOCET_VYNAK FROM VYNAKBYT 
                       WHERE ID_VYROK = mID_VYROK_PARAMETR;
                   COMMIT;
                  raise_application_error( -20010 , qVYRZAL.ID_VYRZAL || ' ID_VYROK ' || mID_VYROK || ' ID_VYROK_PARAMETR ' || mID_VYROK_PARAMETR || 'POCET VZNAK ' || mPOCET_VYNAK || '  ' || mchyba );
                   
         END;     


     END LOOP;
     UPDATE VYROK
        SET CH_PROC_TEPLO = 'X',
            POCET_SPUS_METODY_TEP = mMAX_KRIT_NEMER
        WHERE ID_VYROK = mID_VYROK_PARAMETR;


     PROVED_VYUCTOVANI( ' ID_VYROK = ' || mID_VYROK_PARAMETR , mLIDENT  , 'N' , 'VYROK' , mID_VYNDEV  ,'N' , 'X' , 'N' , NULL );
     
     IF mTransakce = 'A' THEN
       COMMIT;
       SET TRANSACTION READ WRITE ;

     END IF;
 

 END LOOP;



  IF mTransakce = 'A' THEN
    COMMIT ;

  END IF;


end ;

</pre>

`qVYRZAL` is not declared in translated code

**Comment by darold** [comment] 2017-06-21 20:43
Right, fully fixed now with commit ce1dc5d.

**Comment by okbob** [comment] 2017-06-22 03:05
It is fixed in all Oracle codes, that I have. Thank you

**Closed** 2017-06-22 07:02 UTC
