### ISSUE TITLE
Boolean values not converted if REPLACE_AS_BOOLEAN active

### ISSUE THREAD

**Issue by jphiloon** [darold/ora2pg#772] opened 2019-03-12 16:34 UTC
A configuration setting of 
    REPLACE_AS_BOOLEAN	NUMBER:1 CHAR:1 
will indeed create Boolean properties in Postgres.

However, if this setting is enabled during an INSERT, all Boolean properties end up as true.  One must comment this out during INSERT in order for the proper true/false translation to occur.

Ora2Pg v20.0

**Comment by darold** [comment] 2019-03-13 17:35
Hi I'm not able to reproduce the issue. On Oracle:

```
SQL> desc abc
 Nom					   NULL ?   Type
 ----------------------------------------- -------- ----------------------------
 EMAIL_ID					    NUMBER(1)
 LOCKED 					    CHAR(1)
 LOCKED_TIME					    DATE

SQL> SELECT * FROM abc;

  EMAIL_ID L LOCKED_T
---------- - --------
	 1 Y 13/03/19
	 0 N 13/03/19


```
On PostgreSQL:
```
hr=# \d abc
                               Table "hr.abc"
   Column    |            Type             | Collation | Nullable | Default 
-------------+-----------------------------+-----------+----------+---------
 email_id    | boolean                     |           |          | 
 locked      | boolean                     |           |          | 
 locked_time | timestamp without time zone |           |          | 

hr=# SELECT * FROM abc;
 email_id | locked |     locked_time     
----------+--------+---------------------
 t        | t      | 2019-03-13 16:44:41
 f        | f      | 2019-03-13 16:51:09
(2 rows)
```

With ora2pg.conf configuration:
```
REPLACE_AS_BOOLEAN      CHAR:1 NUMBER:1
```

**Comment by jphiloon** [comment] 2019-03-13 18:24
The only thing I left out, thinking it was superfluous, is that the REPLACE_AS_BOOLEAN line had other custom fields as well.  The actual line is

REPLACE_AS_BOOLEAN NUMBER:1 CHAR:1 ANON_USER:ENABLED ANON_USER:PASSWORD_EXPIRED ANON_USER:ACCOUNT_EXPIRED ANON_USER:ACCOUNT_LOCKED USER:ENABLED USER:PASSWORD_EXPIRED USER:ACCOUNT_EXPIRED USER:ACCOUNT_LOCKED LDST_USER:ENABLED LDST_USER:ACCOUNT_LOCKED LDST_USER:ACCOUNT_EXPIRED LDST_USER:PASSWORD_EXPIRED LDST_USER:ENABLED LDST_USER:PASSWORD_EXPIRED PICKLIST:ARCHIVED PICKLIST_ITEM:ARCHIVED

The other thing to note is that the “USER” table is remapped to “app_user” as part of the conversion:
REPLACE_TABLES             user:app_user role:app_role

I’m not sure how these would make a difference, but that’s pretty much the whole story.

Jay

**Comment by darold** [comment] 2019-04-11 12:00
I'm closing this issue as it is not reproducible even with a similar configuration. Oracle:
```
SQL> DESC ABC
 Nom					   NULL ?   Type
 ----------------------------------------- -------- ----------------------------
 EMAIL_ID				   NOT NULL NUMBER
 LOCKED 				   NOT NULL VARCHAR2(1)
 LOCKED_TIME					    TIMESTAMP(6)

SQL> SELECT * FROM ABC;
	 1 Y 11/04/19 13:50:32,000000
	 2 N 11/04/19 13:50:55,000000
```
Here column LOCKED is a varchar2(1) that will be translated as a boolean. As 'Y' and 'N' are automatically detected as boolean values the conversion of data into 't' and 'f' is automatic. See BOOLEAN_VALUES directive for all automatic detection. You can also add your own value to this list.

Using configuration:

```
REPLACE_TABLES  ABC:TEST_BOOLEAN
REPLACE_COLS    ABC(LOCKED:ISLOCKED)
```
the column type is well converted with table and column renaming as well as the default value set to false:
```
CREATE TABLE *test_boolean* (
        email_id bigint NOT NULL,
        *islocked* *boolean* NOT NULL DEFAULT 'f',
        locked_time timestamp
) ;
```
The resulting INSERT statements:
```
INSERT INTO test_boolean (email_id,islocked,locked_time) VALUES (1,'t','2019-04-11 13:50:32.000000');
INSERT INTO test_boolean (email_id,islocked,locked_time) VALUES (2,'f','2019-04-11 13:50:55.000000');
```

**Closed by darold** 2019-04-11 12:00 UTC
