### ISSUE TITLE
Malformed UTF-8 character

### ISSUE THREAD

**Issue by paul511** [darold/ora2pg#1056] opened 2020-12-29 08:21 UTC
$ ora2pg -t SHOW_REPORT --estimate_cost --cost_unit_value 10
Malformed UTF-8 character: \xeb\x69\x6e (unexpected non-continuation byte 0x69, immediately after start byte 0xeb; need 3 bytes, got 1) in substitution (s///) at /opt/oracle/product/19.5/perl/lib/site_perl/5.28.1/Ora2Pg.pm line 11482.
Malformed UTF-8 character (fatal) at /opt/oracle/product/19.5/perl/lib/site_perl/5.28.1/Ora2Pg.pm line 11482.

There are some similar posts, but none in ora2pg 21.0.
Here are answers to questions raised in similar posts:

NLS settings:
$ ora2pg -t show_encoding
[2020-12-29 08:56:56] Ora2Pg version: 21.0
[2020-12-29 08:56:56] Trying to connect to database: dbi:Oracle:host=xxxxx;service_name=yyyy;port=1521
[2020-12-29 08:56:56] Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
[2020-12-29 08:56:56] Current encoding settings that will be used by Ora2Pg:
[2020-12-29 08:56:56]   Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
[2020-12-29 08:56:56]   Oracle NLS_NCHAR AL16UTF16
[2020-12-29 08:56:56]   Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
[2020-12-29 08:56:56]   Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
[2020-12-29 08:56:56]   PostgreSQL CLIENT_ENCODING UTF8
[2020-12-29 08:56:56]   Perl output encoding ''
[2020-12-29 08:56:56] Showing current Oracle encoding and possible PostgreSQL client encoding:
[2020-12-29 08:56:56]   Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
[2020-12-29 08:56:56]   Oracle NLS_NCHAR AL32UTF8
[2020-12-29 08:56:56]   Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
[2020-12-29 08:56:56]   Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
[2020-12-29 08:56:56]   PostgreSQL CLIENT_ENCODING UTF8

Database settings:
SQL> SELECT * FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER = 'NLS_CHARACTERSET';

PARAMETER
--------------------------------------------------------------------------------------------------------------------------------
VALUE
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
NLS_CHARACTERSET
AL32UTF8

In configuration file, I set:
NO_FUNCTION_METADATA    1

**Comment by darold** [comment] 2021-02-20 18:47
I'm closing this issue because it is difficult to know what happen without use case to reproduce.

**Closed by darold** 2021-02-20 18:47 UTC
