### ISSUE TITLE
wrong PERFORM insertion

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#204] opened 2016-06-28 13:06 UTC
`       ####
	# Search direct call to function to add PERFORM before
	####
	foreach my $f (@{$class->{function_list}}) {
		$str =~ s/([;\s]+)$f\s*\(/$1PERFORM \L$f\E\(/igs;
	}`
It inserts PERFORM in such code as `myvar := myfunc();` or 'SELECT ... where ID = myfunc '

**Comment by darold** [comment] 2016-06-29 07:35
Hi,

last commit da05ff5 might fix this issue. Thanks for the report.

Regards,

**Comment by dezdechado** [comment] 2016-06-30 13:37
Hi! Thanks for quick response!
Unfortunately, it doesn't seem right. First of all, we don't need SELECT here either. And, the second, it doesn't cover all cases. You can check on something like:
`myvar1 :=myfunc1();
SELECT myfunc2() INTO myvar2, myfunc3(myfunc4()) INTO myvar3`
Maybe, something like
`$str =~ s/((=|,|\(|SELECT)\s*)PERFORM \L$f\E\(/$1 \L$f\E\(/igs;` 
instead?

**Comment by darold** [comment] 2016-07-01 09:14
Commit 309045f replace the previous fix by replacing variable affectation by a SELECT ... INTO query.
With your example, `myvar1 :=myfunc1();` will be replaced by `SELECT myfunc1() INTO myvar1;`.

**Comment by dezdechado** [comment] 2016-07-04 08:08
Yes, but `SELECT myfunc2() INTO myvar2 from dual` will be replaced by `SELECT PERFORM myfunc2() INTO myvar2`.  And `myfunc3( myfunc4() )` will be replaced by 'myfunc3( PERFORM myfunc4() )'.
By the way, there is no need to replace `myvar1 :=myfunc1();`

**Comment by darold** [comment] 2016-07-04 09:26
Last commit 0b6f78a might solves all cases.

**Comment by dezdechado** [comment] 2016-07-04 13:04
Still no. `myfunc3( myfunc4() )` still will be replaced by 'PERFORM `myfunc3( PERFORM myfunc4() )`. You should add '\(' in first group of `$str =~ s/(?<!=|,)([;\s]+)$f\s*\(/$1PERFORM \L$f\E\(/igs;` (
i.e. `$str =~ s/(?<!=|,\()([;\s]+)$f\s*\(/$1PERFORM \L$f\E\(/igs;` ). I will check it more attentively later. It would be cool to have some kind of unit tests IMHO

**Comment by darold** [comment] 2016-07-04 14:23
I'm not able to reproduce your issue, please send your PL/SQL code to my private email gilles AT darold DOT net.

**Comment by dezdechado** [comment] 2016-07-04 19:37
Create in oracle [http://pastebin.com/avdChpGN](http://pastebin.com/avdChpGN) and export in PostgreSql procedure myfunc3. I've got [http://pastebin.com/Ynj9ujtL](http://pastebin.com/Ynj9ujtL)

**Comment by dezdechado** [comment] 2016-07-04 19:55
By the way, odd symbol `œ` in:
`$str =~ s/SYSDATE/$conv_current_timeœ/igs;`
I think it doesn't worth individual issue

**Comment by darold** [comment] 2016-07-05 07:12
The typo have been fixed in commit  7ae8176 and last commit fb68319 remove the replacement of direct call to functions with PERFORM because there is too much false positive and it require the use of a PL/SQL lexer to be able to do proper conversion. Trying to solve most of the direct function call using regex is obviously a waste of time. Sorry for that.

**Comment by dezdechado** [comment] 2016-07-05 08:23
Well, it's your call. As for me, I would leave the replacement, but only when it's safe. Something like:
`$str =~ s/((;|\bbegin\b|\bloop\b)\s*(--[^\n]*\n)*\s*)$f\s*\(/$1PERFORM \L$f\E\(/igs;`. It should cover most cases, I think. I will try it on my code. 
Feel free to close the issue if it's your final decision. Thanks anyway!

**Comment by darold** [comment] 2016-07-05 09:41
There's too many case where the regex will not work. We really need a pl/sql parser/lexer to handle this kind of replacement. It is on my todo list but it's a work that need huge development time and I don't have enough spare time for that. Maybe in the future but for now I prefer removing this feature.

Best regards,

**Closed by darold** 2016-07-05 09:41 UTC
