### ISSUE TITLE
ora2pg version 20.0 export 

### ISSUE THREAD

**Issue by hotsmile** [darold/ora2pg#995] opened 2020-10-08 11:44 UTC
global_variables.conf  ora2pg.conf  ora2pg-sqm-comm.conf  ora2pg-sqm-intf.conf  ora2pg-sqm-rpt.conf  ora2pg-table.conf
[root@bogon ~]# ora2pg -c ora2pg-sqm-comm.conf
WARNING: target PostgreSQL version must be set in PG_VERSION configuration directive. Using default: 11
[========================>] 1/1 tables (100.0%) end of scanning.     
[========================>] 0/0 sequences (100.0%) end of output.
[========================>] 1/1 tables (100.0%) end of table export.
[========================>] 0/0 views (100.0%) end of output.       
[========================>] 0/0 functions (100.0%) end of functions export.
[========================>] 2/2 procedures (100.0%) end of procedures export.
[========================>] 1/1 packages (100.0%) end of output.             
[========================>] 0/0 types (100.0%) end of output.   
[========================>] 0/0 synonyms (100.0%) end of output.
Fixing function calls in output files...
ERROR: requalify package functions can't read file sqm_comm.sql, No such file or directory

my config file is that 

ORACLE_HOME /usr/lib/oracle/19.8/client64
#ORACLE_DSN  dbi:Oracle:orcl
#ORACLE_DSN  dbi:Oracle:host=182.61.22.200;sid=orcl11g
ORACLE_DSN  dbi:Oracle:host=106.13.26.22;sid=oradb
ORACLE_USER ioe
ORACLE_HOME /usr/lib/oracle/19.8/client64
#ORACLE_DSN  dbi:Oracle:orcl
#ORACLE_DSN  dbi:Oracle:host=182.61.22.200;sid=orcl11g
ORACLE_DSN  dbi:Oracle:host=106.13.26.22;sid=oradb
ORACLE_USER ioe
ORACLE_PWD  xxxxxx
SCHEMA  sqm_comm
TYPE SEQUENCE TABLE VIEW FUNCTION PROCEDURE PACKAGE TYPE SYNONYM
PG_NUMERIC_TYPE    0
PG_INTEGER_TYPE    1
DEFAULT_NUMERIC float
#SKIP    fkeys pkeys ukeys indexes checks
NLS_LANG    AMERICAN_AMERICA.UTF8
OUTPUT     sqm_comm.sql
SCHEMA  sqm_comm
TYPE SEQUENCE TABLE VIEW FUNCTION PROCEDURE PACKAGE TYPE SYNONYM
PG_NUMERIC_TYPE    0
PG_INTEGER_TYPE    1
DEFAULT_NUMERIC float
#SKIP    fkeys pkeys ukeys indexes checks
NLS_LANG    AMERICAN_AMERICA.UTF8
OUTPUT     sqm_comm.sql

**Comment by hotsmile** [comment] 2020-10-08 11:48
why report the error ,the same config apply in version 18.4 ,it's normal

**Comment by darold** [comment] 2020-10-08 18:44
I don't know what happen, I'm not able to reproduce even with the same configuration. To avoid this problem you can disable  PACKAGE_AS_SCHEMA but I guess that you need it.

**Comment by darold** [comment] 2020-10-08 18:46
Or you can simply execute: `touch sqm_comm.sql` in your output directory that should prevent ora2pg to throw the error.

**Comment by darold** [comment] 2020-10-29 08:41
Closing, not reproducible.

**Closed by darold** 2020-10-29 08:41 UTC
