### ISSUE TITLE
Running Ora2pg assessment report for Multiple Schemas in oracle

### ISSUE THREAD

**Issue by Swapnil24051992** [darold/ora2pg#896] opened 2020-06-19 07:07 UTC
I want to run ora2pg migration assessment report for 341 schemas in oracle. Is there anyway i can run the migration report whole at once. I am aware about passing single schema in config file and creating HTML report individually but i am looking for running assessment report for multiple schemas at once

**Comment by darold** [comment] 2020-06-19 08:24
Have a look to ora2pg_scanner.

**Comment by Swapnil24051992** [comment] 2020-06-19 09:45
> Have a look to ora2pg_scanner.

@darold Could you please let me know command for using ora2pg_scanner. I am aware about its concept of creating a csv files and filling it with details like database name ,credentials,schema and all but how to execute that. how can we generate report for multiple schemas at once

**Comment by darold** [comment] 2020-06-19 10:49
```
$ ora2pg_scanner --help

Usage: ora2pg_scanner -l CSVFILE [-o OUTDIR]

   -b | --binpath DIR: full path to directory where the ora2pg binary stays.
   		Might be useful only on Windows OS.
   -c | --config FILE: set custom configuration file to use otherwise ora2pg
		will use the default: /etc/ora2pg/ora2pg.conf.
   -l | --list FILE : CSV file containing a list of databases to scan with
		all required information. The first line of the file
		can contain the following header that describes the
		format that must be used:

		"type","schema/database","dsn","user","password"

   -o | --outdir DIR : (optional) by default all reports will be dumped to a
		directory named 'output', it will be created automatically.
		If you want to change the name of this directory, set the name
		at second argument.

   -t | --test : just try all connections by retrieving the required schema
		 or database name. Useful to validate your CSV list file.

   Here is a full example of a CSV databases list file:

	"type","schema/database","dsn","user","password"
	"MYSQL","sakila","dbi:mysql:host=192.168.1.10;database=sakila;port=3306","root","secret"
	"ORACLE","HR","dbi:Oracle:host=192.168.1.10;sid=XE;port=1521","system","manager"

   The CSV field separator must be a comma.

   Note that if you want to scan all schemas from an Oracle instance you just
   have to leave the schema field empty, Ora2Pg will automatically detect all
   available schemas and generate a report for each one. Of course you need to
   use a connection user with enough privileges to be able to scan all schemas.
   For example:

	"ORACLE","","dbi:Oracle:host=192.168.1.10;sid=XE;port=1521","system","manager"

   will generate a report for all schema in the XE instance. Note that in this
   case the SCHEMA directive in ora2pg.conf must not be set.
```

or chapter "Global Oracle and MySQL migration assessment" of the documentation.

**Comment by Swapnil24051992** [comment] 2020-06-19 13:03
@darold  Thanks for instant reply
I am facing following issue while running scanner:
Can't connect to data source ''dbi:Oracle:host=localhost;SID=ORCL;port=1521'' because I can't work out what driver to use (it doesn't seem to contain a 'dbi:driver:' prefix and the DBI_DRIVER env var is not set) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 1624.
Running: ora2pg -c ora2pg.conf -t SHOW_REPORT --dump_as_html --estimate_cost -s 'dbi:Oracle:host=localhost;SID=ORCL;port=1521' -n 'CDI' >> "output/schema_CDI-report.html"

Could you help me out with this

**Comment by Swapnil24051992** [comment] 2020-06-25 08:41
> @darold Thanks for instant reply
> I am facing following issue while running scanner:
> Can't connect to data source ''dbi:Oracle:host=localhost;SID=ORCL;port=1521'' because I can't work out what driver to use (it doesn't seem to contain a 'dbi:driver:' prefix and the DBI_DRIVER env var is not set) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 1624.
> Running: ora2pg -c ora2pg.conf -t SHOW_REPORT --dump_as_html --estimate_cost -s 'dbi:Oracle:host=localhost;SID=ORCL;port=1521' -n 'CDI' >> "output/schema_CDI-report.html"
> 
> Could you help me out with this

**Comment by Swapnil24051992** [comment] 2020-06-25 08:42
@darold Could you please provide me with your help for the above issue i posted last week

**Comment by darold** [comment] 2020-06-27 06:42
Duplicate of #905

**Closed by darold** 2020-06-27 06:42 UTC
