### ISSUE TITLE
"Segmentation fault" while extracting data from Oracle

### ISSUE THREAD

**Issue by Melade** [darold/ora2pg#627] opened 2018-01-29 10:42 UTC
Hi,

I have a problem whith an extraction, after several try the error occure always at the same time.

[========================>] 0/0 rows (100.0%) Table NV2 (0 recs/sec)
[=====================>   ] 6649312/7268477 total rows (91.5%) - (2537 sec., avg: 2620 recs/sec).
Erreur de segmentation>   ] 6509538/7268477 rows (89.6%) on total estimated data (2537 sec., avg: 2565 recs/sec)

I export only the table that crahes and apparently there is problem since the line 4 of the table of 38 rows.. and when I exclude this table from the extraction there is no problem.

Here the definition of the table..

 CREATE TABLE "APW"."OLE" 
   (	"REFESOC" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"RFENTLOS15" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"RFREFE1OLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RFREFE2OLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RFREFE3OLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RFREFE4OLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RFREFE5OLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LVLIENOLE" LONG RAW, 
	"FGTAOLEOLE" NUMBER(1,0), 
	"LVNOTEOLE" VARCHAR2(2000 BYTE), 
	"ROWGSA" VARCHAR2(25 BYTE), 
	"LIENHYPERT" VARCHAR2(2048 BYTE), 
	 CONSTRAINT "OLE_PK" PRIMARY KEY ("REFESOC", "RFENTLOS15", "RFREFE1OLE", "RFREFE2OLE", "RFREFE3OLE", "RFREFE4OLE", "RFREFE5OLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TSAPW"  ENABLE, 
	 CONSTRAINT "OLE_SOC_FK01" FOREIGN KEY ("REFESOC")
	  REFERENCES "APW"."SOC" ("REFESOC") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TSAPW" ;
 

  CREATE OR REPLACE TRIGGER "APW"."ROWID_OLE" before update or insert on OLE for each row
declare
	strRowid VARCHAR2(18);
	nCount NUMBER(6);
begin

	SELECT ROWIDTOCHAR(:new.rowid) INTO strRowid FROM dual;
	nCount := TO_NUMBER( NVL ( SUBSTR( :old.rowgsa, 20, 6 ), '0' ) );
	IF nCount = 999999 THEN
		nCount := 0;
	END IF;
	nCount := nCount + 1;
	:new.rowgsa := strRowid || '-' || SUBSTR(TO_CHAR( nCount, '099999' ), 2, 6 );

end;
/
ALTER TRIGGER "APW"."ROWID_OLE" ENABLE;

The 4th lines of the table : 

Insert into OLE (REFESOC,RFENTLOS15,RFREFE1OLE,RFREFE2OLE,RFREFE3OLE,RFREFE4OLE,RFREFE5OLE,LVLIENOLE,FGTAOLEOLE,LVNOTEOLE,ROWGSA,LIENHYPERT) values ('250','2','990000000110','*','*','*','*',null,'0',null,'00000000.0000.0000-000001',null);

Insert into OLE (REFESOC,RFENTLOS15,RFREFE1OLE,RFREFE2OLE,RFREFE3OLE,RFREFE4OLE,RFREFE5OLE,LVLIENOLE,FGTAOLEOLE,LVNOTEOLE,ROWGSA,LIENHYPERT) values ('520','2','450','*','*','*','*',null,'0','2000/39
','00000000.0000.0000-000001',null);

Insert into OLE (REFESOC,RFENTLOS15,RFREFE1OLE,RFREFE2OLE,RFREFE3OLE,RFREFE4OLE,RFREFE5OLE,LVLIENOLE,FGTAOLEOLE,LVNOTEOLE,ROWGSA,LIENHYPERT) values ('520','2','200000000001','*','*','*','*',null,'0','GBXGNBXNGN','00000000.0000.0000-000001',null);

the problematic one
Insert into OLE (REFESOC,RFENTLOS15,RFREFE1OLE,RFREFE2OLE,RFREFE3OLE,RFREFE4OLE,RFREFE5OLE,LVLIENOLE,FGTAOLEOLE,LVNOTEOLE,ROWGSA,LIENHYPERT) values ('520','2','200000000002','*','*','*','*',null,'0',null,'00000000.0000.0000-000001',null);

I joined the extracting log of the table and the output log  

[APW_ABELPRD.log](https://github.com/darold/ora2pg/files/1673141/APW_ABELPRD.log)
[APW_ABELPRD_output.log](https://github.com/darold/ora2pg/files/1673146/APW_ABELPRD_output.log)

I also tried the last commit [https://github.com/darold/ora2pg/commit/5e166ccfa21fb6bb4546e651a5e6163b09c1cb5d](url) but it doesn't solve the problem..

Thanks for your help ..

ML

**Comment by Melade** [comment] 2018-01-29 16:40
Hi 
I was looking at the others issues and when I saw this one : [https://github.com/darold/ora2pg/issues/426] 
I found that this problem might look like mine because 2 columns have big varchar values.
So I disabled the NO_LOB_LOCATOR  value and tried the export on the table it works ! 
So I did it for the full Schema and it works too as well.
I 'm gonna check the data and tell you back.

**Comment by darold** [comment] 2018-01-31 08:29
Hi,

Please have a look to the Ora2Pg documentation about LONG RAW. This is an obsolete Oracle type that have been replaced by BLOB a long time ago. You need to convert them to BLOB before.

Regards,

**Comment by Melade** [comment] 2018-01-31 16:25
Hi,

Thanks for your answer. 

I'm not sure to understand : so these two columns are considered as LONG RAW  ?
"LVNOTEOLE" VARCHAR2(2000 BYTE),
 "LIENHYPERT" VARCHAR2(2048 BYTE),

And I have to do the following ?

  _Exporting LONG RAW
    If you still have columns defined as LONG RAW, Ora2Pg will not be able
    to export these kind of data. The OCI library fail to export them and
    always return the same first record. To be able to export the data you
    need to transform the field as BLOB by creating a temporary table before
    migrating data. For example, the Oracle table:

            SQL> DESC TEST_LONGRAW
             Name                 NULL ?   Type
             -------------------- -------- ----------------------------
             ID                            NUMBER
             C1                            LONG RAW

    need to be "translated" into a table using BLOB as follow:

            CREATE TABLE test_blob (id NUMBER, c1 BLOB);

    And then copy the data with the following INSERT query:

            INSERT INTO test_blob SELECT id, to_lob(c1) FROM test_longraw;

    Then you just have to exclude the original table from the export (see
    EXCLUDE directive) and to renamed the new temporary table on the fly
    using the REPLACE_TABLES configuration directive._

Regards

**Comment by darold** [comment] 2018-03-24 09:55
Hi, I don't know about what works with NO_LOB_LOCATOR enabled, if you can send me a dump of this table to reproduce the problem I will try to find an explanation. I'm closing this issue because the way to fix it is known and documented.

**Closed by darold** 2018-03-24 09:55 UTC
