### ISSUE TITLE
missing no logging tables

### ISSUE THREAD

**Issue by MichaelDBA** [darold/ora2pg#386] opened 2017-05-02 14:11 UTC
How do you get table DDL for oracle non logging tables?  Right now, I only get tables that have logging enabled.

**Comment by MichaelDBA** [comment] 2017-05-02 18:53
Actually after I changed the tables to logging, it still wouldn't pick up some tables that I can view in sqldeveloper and sqlplus with the same credentials I run ora2pg with.  One thing I noticed in common across these tables is that the ones with no rows are not picked up, only the tables with rows (all_tables.num_rows > 0).

**Comment by darold** [comment] 2017-05-04 13:33
Ora2Pg extract all tables that are not marked as temporary tables or not logged table, but the query used to extract tables is like the following:
```
SELECT * FROM ALL_TABLES A, ALL_OBJECTS O
WHERE A.OWNER=O.OWNER
    AND A.TABLE_NAME=O.OBJECT_NAME
    AND O.OBJECT_TYPE='TABLE' AND A.TEMPORARY='N'
    AND (A.NESTED != 'YES' OR A.LOGGING != 'YES')
    AND A.SECONDARY = 'N' AND A.OWNER='XXXX';
```

But I don't know if UNLOGGED tables in Oracle are a user voluntary design or if this this exclusively "system" tables. It's not a big work to export these table as UNLOGGED table under PostgreSQL but I need to know if this is a kind of table that might be exported or not. In my experience most of them was some DBMS internal tables that must not be exported. In your side what is the use of these kind of tables?

**Comment by MichaelDBA** [comment] 2017-05-04 18:15
With that SQL above, I found the table, but it is not being output via ora2pg.  Here is the table def:
```
CREATE TABLE "GMACM"."RTRNFILE" 
   (	"BATCHID" VARCHAR2(30 BYTE), 
	"SEGMENT" VARCHAR2(1 BYTE), 
	"RETURNSEQ" NUMBER(38,0), 
	"RETURNDATE" DATE, 
	"BATCHSEQ" NUMBER(38,0), 
	"REC_COUNT" NUMBER(38,0), 
	 CONSTRAINT "UNQ_RTRNFILE_BATCHID_SEGMENT" UNIQUE ("BATCHID", "SEGMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 COMPRESS BASIC LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
```
Attached is my ora2pg conf file
[ora2pg_gmacm.txt](https://github.com/darold/ora2pg/files/977152/ora2pg_gmacm.txt)

From all_tables, it shows that this table is logged and it is not a temporary table.  So I can't figure it out.

On another note, I think Oracle Global Temp tables should not be exported like you do now, but I do think unlogged tables should be exported.  Just don't export the data for those tables.

Any other ideas about why this one table won't come out? RTRNFILE?

**Comment by darold** [comment] 2017-05-06 09:31
Export of unlogged table was broken and exported as normal table, commit 1c51bb4 fix that. SHOW_TABLE will now mark table unlogged in the output.

Using the DDL above to create table "GMACM"."RTRNFILE"  works on my Oracle export, I think you can not see it because this table is in you EXCLUDE list :-) For better readability if you want you can use multiple time the EXCLUDE directive in the configuration file.

**Comment by MichaelDBA** [comment] 2017-05-06 12:22
Dag!  Nice catch, Darold, yeah freakin table is in the exlude list by default.  Also, thanks for fixing unlogged tables bug.

**Comment by MichaelDBA** [comment] 2017-05-06 12:27
Hi Darold, I reopened this issue because I thought RTRNFILE was an oracle special table, but I cannot find anything about the RTRNFILE associated with Oracle. How did that get into the default exclusion list?

**Comment by darold** [comment] 2017-05-06 16:30
This seems related to Record To Report, the default exclusion list is internal and must be change with a commit. Is this the only table that must be excluded or is there any other RTR* named table?

**Comment by MichaelDBA** [comment] 2017-05-07 10:06
This appears to be the only table on the exclusion list.

**Comment by MichaelDBA** [comment] 2017-05-11 13:05
related question:  how does this table exclusion list get populated.  I am now not able to export the table, HCIPAT_SUBROGATION_CLAIM.  I did a google on that and I can not find it anywhere, so how did you put this table into the exclusion list.  What's the logic?

**Comment by darold** [comment] 2017-05-11 14:55
You have the EXCLUDE directive. Setting:
```
EXCLUDE     TABLE[RTRNFILE]
```
Internally in lib/Ora2Pg.pm there is an array of regexp that are used to exclude system table. Here is its actual definition:
```
our @EXCLUDED_TABLES = ('USLOG\$_.*', 'MLOG\$_.*', 'RUPD\$_.*', 'MDXT_.*', 'MDRT_.*', 'MDRS_.*', 'DR\$.*', 'CLI_SWP\$.*', 'LOGMNR\$.*', 'REPCAT\$.*', 'JAVA\$.*','AQ\$.*','BIN\$.*','SDO_GR_.*','.*\$JAVA\$.*','PROF\$.*','TOAD_PLAN_.*','SYS_.*\$');
```
If you table is not concerned by one of these regexp and not by one entry in the EXCLUDE directive, then the issue is not here. Do you have the full definition of this table?

**Closed** 2017-05-12 09:21 UTC
