### ISSUE TITLE
Wide character in subroutine entry 

### ISSUE THREAD

**Issue by dustymc** [darold/ora2pg#808] opened 2019-08-06 22:13 UTC
I have ora2pg 20.0, pG 11.2, Oracle 11.2.0.1.0, perl v5.10.1

I am attempting direct copy. It seems to work well with varchar2(255) and smaller. All tables with varchar>255 fail with...

```

-bash-4.1$ /usr/local/bin/ora2pg -t COPY -o table.sql -b /usr/local/tmp/ora2pg -c /hxxxx/xx.conf 
[========================>] 1/1 tables (100.0%) end of scanning.   
Wide character in subroutine entry at /usr/local/share/perl5/Ora2Pg.pm line 14486.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=xxx)(PROTOCOL=tcp)(PORT=1521))(CONNECT_DATA=(SID=xxx))) at /usr/local/share/perl5/Ora2Pg.pm line 14486.
```

I've turned encoding on and off in the .conf file to no affect, and I'm using the defaults anyway.

```

Current encoding settings that will be used by Ora2Pg:
	Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
	Oracle NLS_NCHAR AL32UTF8
	Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
	Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
	PostgreSQL CLIENT_ENCODING UTF8
	Perl output encoding ''
Showing current Oracle encoding and possible PostgreSQL client encoding:
	Oracle NLS_LANG AMERICAN_AMERICA.AL32UTF8
	Oracle NLS_NCHAR AL32UTF8
	Oracle NLS_TIMESTAMP_FORMAT YYYY-MM-DD HH24:MI:SS.FF6
	Oracle NLS_DATE_FORMAT YYYY-MM-DD HH24:MI:SS
	PostgreSQL CLIENT_ENCODING UTF8

```
I'm testing with one table

```
ALLOW ADDR

```

Oracle:

```
desc addr
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 ADDR_ID							   NOT NULL NUMBER
 STREET_ADDR1							   NOT NULL VARCHAR2(255)
 STREET_ADDR2								    VARCHAR2(255)
 CITY								   NOT NULL VARCHAR2(60)
 STATE									    VARCHAR2(20)
 ZIP									    VARCHAR2(10)
 COUNTRY_CDE								    VARCHAR2(50)
 MAIL_STOP								    VARCHAR2(20)
 FORMATTED_ADDR 							    VARCHAR2(510)
 AGENT_ID							   NOT NULL NUMBER
 ADDR_TYPE							   NOT NULL VARCHAR2(25)
 JOB_TITLE								    VARCHAR2(60)
 VALID_ADDR_FG							   NOT NULL NUMBER
 ADDR_REMARKS								    VARCHAR2(255)
 INSTITUTION								    VARCHAR2(255)
 DEPARTMENT								    VARCHAR2(255)
```
PG (built with ora2pg)
```
\d addr
                           Table "public.addr"
     Column     |          Type          | Collation | Nullable | Default 
----------------+------------------------+-----------+----------+---------
 addr_id        | bigint                 |           | not null | 
 street_addr1   | character varying(255) |           | not null | 
 street_addr2   | character varying(255) |           |          | 
 city           | character varying(60)  |           | not null | 
 state          | character varying(20)  |           |          | 
 zip            | character varying(10)  |           |          | 
 country_cde    | character varying(50)  |           |          | 
 mail_stop      | character varying(20)  |           |          | 
 formatted_addr | character varying(510) |           |          | 
 agent_id       | bigint                 |           | not null | 
 addr_type      | character varying(25)  |           | not null | 
 job_title      | character varying(60)  |           |          | 
 valid_addr_fg  | bigint                 |           | not null | 
 addr_remarks   | character varying(255) |           |          | 
 institution    | character varying(255) |           |          | 
 department     | character varying(255) |           |          | 
```

Any clues greatly appreciated!

**Comment by darold** [comment] 2019-08-07 07:36
Please update to latest development code and report the error message again so I will have the exact line number where the issue happen.

**Comment by darold** [comment] 2019-08-07 09:29
Also can you try to use a more recent version of Perl, v5.10 is ten years old, support to unicode has been really improved since this time.

**Comment by dustymc** [comment] 2019-08-07 13:48
>latest development code 

As far as I know that's what I have - can you be more specific, and I apologize in advance if I'm missing something obvious.

>Perl

On it...

**Comment by darold** [comment] 2019-08-07 14:07
Latest development code can be downloaded using:
```
git clone git@github.com:darold/ora2pg.git
cd ora2pg/
```
or if you prefer:
```
wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
```
then build and install:
```
perl Makefile.PL
make
sudo make install
```

**Comment by dustymc** [comment] 2019-08-16 20:30
Thank you. I now have the latest ora2pg and a new copy of perl

```
 perl --version

This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux
```


Here's the error from COPY

```

[========================>] 1/1 tables (100.0%) end of scanning.   
Wide character in subroutine entry at /usr/local/share/perl5/Ora2Pg.pm line 14567.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(HOST=dxxxxedu)(PROTOCOL=tcp)(PORT=xx))(CONNECT_DATA=(SID=xxx))) at /usr/local/share/perl5/Ora2Pg.pm line 14567.
```

I confirmed that everything still works with varchar2(255).

**Comment by darold** [comment] 2019-08-16 21:38
OK good. The problem seems related to non utf-8 character sent by Oracle even if we ask UTF8 encoding. I guess that if you try to export the table to file with Ora2Pg it is the same? Comment the PG_DSN configuration directive and export using `-t COPY -a 'ADDR'` option to ora2pg you will have a file output.sql or ADDR_output.sql generated. Normally the same error should happen otherwise there is a problem with the call of DBD::Pg::pg_putcopydata() function.

If the same error occurs try to set NLS_LANG to something like AMERICAN_AMERICA.WE8ISO8859P1 and LATIN1 for this particular table or any other encoding you think must be necessary, corean, japanese, etc.

**Comment by dustymc** [comment] 2019-08-16 23:27
I commented out the PG_ bits and...

[========================>] 1/1 tables (100.0%) end of scanning.   
[========================>] 2897/2324 rows (124.7%) Table ADDR (2897 recs/sec)
[========================>] 2897/2324 total rows (124.7%) - (1 sec., avg: 2897 recs/sec).
[========================>] 2324/2324 rows (100.0%) on total estimated data (1 sec., avg: 2324 recs/sec)


The import then failed because of some check constraints (which is likely just funky data, this is an old table).

psql:/usr/local/tmp/ora2pg/table.sql:2902: ERROR:  new row for relation "addr" violates check constraint "ck_department_noprint"
DETAIL:  Failing row contains (1000032, Base postale N°51, null, Paris, 55, rue Buffon, 75005, null, null, Alexandre Hassanin
Muséum National d'Histoire Naturelle
UMR 520..., 1014344, Shipping, null, 1, null, Muséum National d'Histoire Naturelle, UMR 5202 - Origine, Structure, et Evolution de la Biodiversité).

I dropped the constraints and it imported successfully. 

I deleted that, and direct copy still fails. 


[========================>] 1/1 tables (100.0%) end of scanning.   
Wide character in subroutine entry at /usr/local/share/perl5/Ora2Pg.pm line 14567.

I tried AMERICAN_AMERICA.WE8ISO8859P1  and got a different error:

   
DBD::Pg::db pg_putcopyend failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xb0
CONTEXT:  COPY addr, line 76 at /usr/local/share/perl5/Ora2Pg.pm line 14578.
FATAL: ERROR:  invalid byte sequence for encoding "UTF8": 0xb0
CONTEXT:  COPY addr, line 76
Aborting export...

As far as I know the data are in fact UTF. MOST things are ASCII, but there are various characters in various places.

I tried direct copy with a table that has a lot of not-ASCII.


[========================>] 1/1 tables (100.0%) end of scanning.          
DBD::Pg::db pg_putcopyend failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xf3 0x6e 0x20 0x61
CONTEXT:  COPY common_name, line 101 at /usr/local/share/perl5/Ora2Pg.pm line 14578.
FATAL: ERROR:  invalid byte sequence for encoding "UTF8": 0xf3 0x6e 0x20 0x61
CONTEXT:  COPY common_name, line 101
DBI::db=HASH(0x3eaf938)->disconnect invalidates 1 active statement handle (either destroy statement handles or call finish on them before disconnecting) at /usr/local/share/perl5/Ora2Pg.pm line 13744.
Aborting export...


removed PG stuff

...COPY

[======================>  ] 297016/320007 rows (92.8%) Table COMMON_NAME (27001 recs/sec)
[======================>  ] 297016/320007 total rows (92.8%) - (11 sec., avg: 27001 recs/sec).
[========================>] 320007/320007 rows (100.0%) on total estimated data (11 sec., avg: 29091 recs/sec)


import and

select count(*) from common_name;
 count  
--------
 297016
(1 row)


That path seems to be handling UTF correctly.

```
xx=> select common_name from common_name where taxon_name_id=1991795;
      common_name       
------------------------
 Vipère de Russell
 Dabois
 Vipera di Russel
 Russels hugorm
 Kettenviper
 Russell's Viper
 Russelinkyy
 vattakoora
 retha aunali
 pili kandhodi
 Indian Russell's viper
 chandra bora
 ಮಂಡಲದ ಹಾವು
 ngu maew sao
 రక్తపింజర
 അണലി
 තිත් පොලඟා
 కాటుక రేకుల పాము
 mwe lewe
 chandan boda
 thavitta
 Tawarya
 chain snake
 rakta anali
 উলূবোড়া
 scissors snake
 khadchitalo
 katuka rekula paamu
 koraile
 raktamandali
 घोणस, घोण्या
 raktha penjara
 chenathandan
 seven pacer
 uloo bora
 raktha penjari
 kannadi viriyan
 বোড়া
 thith polonga
 bora
 ghonas
 दबौया
 mandaladha haavu
 chain viper
 chitalo
 চন্দ্রবোড়া
 kolakumandala
 daboia
 gunas
 கண்ணாடி விரியன்
 Russel’s Viper
```

I appreciate your help with this, and thank you for making this tool available. If there isn't an easy solution to this, I think going through text can be made to work well enough.

**Comment by darold** [comment] 2019-08-16 23:33
Unfortunately I don't know what happens and if I don't have the Oracle database to try different thing it is complicated to help to find a solution.

**Comment by darold** [comment] 2020-09-18 11:00
With latest development code I can not reproduce the issue there was probably some non utf-8 characters in the Oracle data, I'm closing the issue.

**Closed by darold** 2020-09-18 11:00 UTC
