### ISSUE TITLE
XMLTYPE columns are truncated around 32K

### ISSUE THREAD

**Issue by smil2k** [darold/ora2pg#889] opened 2020-06-13 20:45 UTC
I have a table which contains XML columns. After a clean export, the file contains truncated column data. The original column contained 32620 chars.

Probably XMLTYPE columns were not recognized as CLOB, datalimit was 10000 (instead of 1000 like for blobs). NO_LOB_LOCATOR 0, LONGREADLEN is unset.

**Comment by darold** [comment] 2020-06-14 04:43
Recent commit b853340 might have fixed that, upgrade to latest development code.

**Comment by smil2k** [comment] 2020-06-14 11:46
I was on 60aa30e which includes the one you mentioned.

**Comment by darold** [comment] 2020-06-14 18:37
Does the data are truncated or does the data are like `OCILobLocatorPtr=SCALAR(0x560d3db8ed38)`?

**Comment by smil2k** [comment] 2020-06-14 19:37
It is cut. The scalar thing is already fixed by the commit you mentioned. Just my xmls were under 32k sofar.

**Comment by darold** [comment] 2020-06-27 07:38
With Oracle 12c I'm not able to reproduce the problem using a XML of 44610 bytes everything is exported. NO_LOB_LOCATOR to 0 and LONGREADLEN to default (1024000). What is your version of Oracle database?

**Comment by smil2k** [comment] 2020-06-28 19:49
Do you have an idea how to catch this? It seems our oracle 12.0.2 behaves different in some respect than others. 
My estimation for the largest xml was around 76k. Only 2-3 records were truncated. I've checked, they were correct in ora.

**Comment by darold** [comment] 2021-03-22 21:48
I'm closing this issue as not reproducible, I have tried again with XML data > 80k and everything is exported. The only thing is that when XML_PRETTY is enabled I have the error:
```
 FATAL: ORA-19011: Character string buffer too small
ORA-06512: at "SYS.XMLTYPE", line 169 (DBD ERROR: error possibly near <*> indicator at char 49 in 'SELECT "POID",a."PODOC".extract('/').getStringVal<*>() FROM "HR"."PO_XML_TAB" a')
```
The pretty print can b e done later in PostgreSQL.

**Closed by darold** 2021-03-22 21:48 UTC
Labels: bug
