### ISSUE TITLE
Exception with packages export

### ISSUE THREAD

**Issue by chaluvadi286** [darold/ora2pg#994] opened 2020-10-08 10:39 UTC
I am getting below exception while exporting Oracle packages and process is getting aborted.

Nested quantifiers in regex; marked by <-- HERE in m/\b/** <-- HERE ***********************************************************************************\b/ at D:/work/ICC/strawberry/perl/site/lib/Ora2Pg.pm line 18094.

I am not able to find out exact reason, request your help. I re-installed Perl & Ora2Pg master version from GitHub on 30th Sep 20

**Comment by darold** [comment] 2020-10-08 10:45
Please upgrade to latest development code this problem have been fixed.

**Comment by chaluvadi286** [comment] 2020-10-08 12:41
Thanks Darold, this error is gone with latest build. One observation from earlier releases - Looks like you are taking DEFAULT NULL
parameters also as good as no default value and Ora2Pg is changing order of parameters. Is there any specific reason why this was done?

**Comment by darold** [comment] 2020-10-08 12:54
Do you have an Oracle DDL example so that I can better understand what you mean (I just need the CREATE FUNCTION header not the body).

**Comment by chaluvadi286** [comment] 2020-10-08 13:01
Oracle procedure - 
create or replace PROCEDURE "SP_CHANGE" (
	vBrnNum 				IN NUMBER ,
	vSwift_CCY 			IN VARCHAR2,
	vMode 					IN VARCHAR2 DEFAULT 'EOD',
	vIndex_Code 		IN VARCHAR2 DEFAULT NULL
)

output from converted file -
-- WARNING: parameters order has been changed by Ora2Pg to move parameters with default values at end
-- Original order was: sp_change( vBrnNum numeric , vSwift_CCY text, vMode text DEFAULT 'EOD', vIndex_Code text )
-- You will need to manually reorder parameters in the function calls
CREATE OR REPLACE PROCEDURE sp_change ( vBrnNum numeric , vSwift_CCY text, vIndex_Code text , vMode text DEFAULT 'EOD') AS $body$

**Comment by darold** [comment] 2020-10-08 13:18
The point is that any parameters following a parameter with a default value must have a default value otherwise you will have error:
```
ERROR:  input parameters after one with a default value must also have defaults
```
The problem here is that Ora2Pg remove the DEFAULT NULL because it is useless as the value is always NULL by default, but not in this case.

I remember that I was asked to not reorder parameters but just add DEFAULT NULL to all following parameters without a DEFAULT value. I will try to work on this in the next days.

**Comment by darold** [comment] 2020-10-08 18:04
Commit 62a4664 might fix this problem, can you please give a try to latest development code and let me know?

**Comment by chaluvadi286** [comment] 2020-10-09 10:52
Thanks Darold for quick help. One minor observation - if first default parameter is having DEFAULT NULL then it is removing DEFAULT NULL. For eg- Oracle declaration is

create or replace PROCEDURE "SP_DF_EOD"
	(
		vBrnNum	  							IN NUMBER ,
		vStatus	  							OUT NUMBER,
		vSwift_CCYCode					IN VARCHAR2 DEFAULT NULL,
		vZeroDFOnly  						IN CHAR DEFAULT 'N',
    vIndex_Code             IN VARCHAR2  DEFAULT NULL
	)

Converted procedure is having - 
CREATE OR REPLACE PROCEDURE sp_mm_calculate_df_eod ( vBrnNum numeric , vStatus INOUT numeric, vSwift_CCYCode text, vZeroDFOnly CHAR DEFAULT 'N', vIndex_Code text  DEFAULT NULL) AS $body$

If you look at the parameter # vSwift_CCYCode, DEFAULT NULL is missing

**Comment by darold** [comment] 2020-10-09 12:13
Fixed in last commit 554f098, thanks for testing.

**Comment by edelanoe** [comment] 2021-04-08 14:45
Hello Darold,
This change has an unwanted consequence: if there is an OUT parameter after a parameter with default value, ora2pg adds "DEFAULT NULL" to the OUT parameter.
This causes error "only input parameters can have default values".
Can you reopen ?
E.D.

**Comment by edelanoe** [comment] 2021-04-08 15:44
Note that Postgres compiles successfully when an OUT parameter (without default) is located after params with default values.

**Comment by darold** [comment] 2021-04-08 22:12
Commit 5a25305 might solve this problem, it also replace any call to `RETURN(...);` to a function that doesn't have RETURNS clause which is the case for a function with OUT parameters.

**Comment by edelanoe** [comment] 2021-04-20 10:16
Hello Gilles,

Sorry, I see a regression:
Oracle:
CREATE OR REPLACE PACKAGE BODY PCK_CUST AS

    FUNCTION CVS_HEADER RETURN VARCHAR2 is
    -- A mettre systématiquement afque le schéma Pg puisse avoir sa version
    BEGIN
        -- Commentaire de Package --
        -- (ne sera conservé en PostgreSQL que s'il est ici)
        -- API de manipulation des tables de paramètres via l'IHM PTM_WD
        --
        -- Numéro de Version à rendre visible en prod: Révision de fichier CVS
        return '$Header: /cvsstore/GEAPARK2012/SourcesOracle/SCRIPTS_BDD/Install/COMMUN/GEADBA/Packages/PCK_CUST.sql,v 1.12 2021/04/15 17:46:01 edelanoe Exp $';
    END CVS_HEADER;

    PROCEDURE local_raise_error(p_sgbd_code varchar2, p_errmsg varchar2) is
    BEGIN
    -- Desc:
    -- Appel qui loggue en TRX autonome lors de la génération de l'erreur (niveau le plus bas)
        PCK_BDD.app_raise_error(p_sgbd_code, p_errmsg, 'PCK_CUST');
    END;

Postgres generated by v21.1 master , the 2021/04/16  (wrong part in **bold**)
DROP SCHEMA IF EXISTS pck_cust CASCADE;
CREATE SCHEMA IF NOT EXISTS pck_cust;
CREATE OR REPLACE FUNCTION pck_cust.cvs_header () RETURNS varchar AS $body$
DECLARE

    -- A mettre systématiquement afque le schéma Pg puisse avoir sa version
BEGIN
        -- Commentaire de Package --
        -- (ne sera conservé en PostgreSQL que s'il est ici)
        -- API de manipulation des tables de paramètres via l'IHM PTM_WD
        --
        -- Numéro de Version à rendre visible en prod: Révision de fichier CVS
        return '$Header: /cvsstore/GEAPARK2012/SourcesOracle/SCRIPTS_BDD/Install/COMMUN/GEADBA/Packages/PCK_CUST.sql,v 1.7 2021/02/02 18:13:25 edelanoe Exp $';
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION pck_cust.cvs_header () FROM PUBLIC;

**CREATE OR REPLACE FUNCTION pck_cust.local_raise_error (p_sgbd_code text, p_errmsg text) RETURN;
    END;**

-- pre-processing gestion d'erreur fait à partir d'ici
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION pck_cust.local_raise_error (p_sgbd_code text, p_errmsg text) FROM PUBLIC;

Postgresql generated by v20.0 (correct):
DROP SCHEMA IF EXISTS pck_cust CASCADE;
CREATE SCHEMA pck_cust;
CREATE OR REPLACE FUNCTION pck_cust.cvs_header () RETURNS varchar AS $body$
DECLARE

    -- A mettre systématiquement afque le schéma Pg puisse avoir sa version
BEGIN
        -- Commentaire de Package --
        -- (ne sera conservé en PostgreSQL que s'il est ici)
        -- API de manipulation des tables de paramètres via l'IHM PTM_WD
        --
        -- Numéro de Version à rendre visible en prod: Révision de fichier CVS
        return '$Header: /cvsstore/GEAPARK2012/SourcesOracle/SCRIPTS_BDD/Install/COMMUN/GEADBA/Packages/PCK_CUST.sql,v 1.7 2021/02/02 18:13:25 edelanoe Exp $';
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION pck_cust.cvs_header () FROM PUBLIC;

CREATE OR REPLACE FUNCTION pck_cust.local_raise_error (p_sgbd_code text, p_errmsg text) RETURNS VOID AS $body$
BEGIN
    -- Desc:
    -- Appel qui loggue en TRX autonome lors de la génération de l'erreur (niveau le plus bas)
        PERFORM PCK_BDD.app_raise_error(p_sgbd_code, p_errmsg, 'PCK_CUST');
    END;

-- pre-processing gestion d'erreur fait à partir d'ici
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION pck_cust.local_raise_error (p_sgbd_code text, p_errmsg text) FROM PUBLIC;

Can you do something ?
Rgds

**Comment by edelanoe** [comment] 2021-04-27 17:40
Hello Darold,

I have a shorter piece of code that reproduces the issue. Please see attachments. Oracle code is in the .sql.ora , generated code in the .sql, and postgres log in the .log.

Rgds,
Eric
[PCK_CUST_demo.zip](https://github.com/darold/ora2pg/files/6386519/PCK_CUST_demo.zip)

**Comment by darold** [comment] 2022-07-10 07:37
This is fixed in current development code. Current output of the test case above is:
```
CREATE OR REPLACE PROCEDURE pck_cust_demo.local_raise_error (p_sgbd_code text, p_errmsg text) AS $body$
BEGIN
        PCK_BDD.app_raise_error(p_sgbd_code, p_errmsg, 'PCK_CUST_DEMO');
    END;

END;
$body$
LANGUAGE PLPGSQL
;
```

**Closed by darold** 2022-07-10 07:37 UTC
Labels: bug, enhancement
