### ISSUE TITLE
Oracle functions are not marked as STABLE

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#286] opened 2017-02-03 13:54 UTC
I know so following proposal is little bit controversial. ora2pg translate all Oracle functions as volatile PostgreSQL functions. Oracle disallow any changes of db in functions - so functions can be marked as STABLE. This can fail when function returns some random content. 

Motivation - the STABLE functions significantly better optimized when it is used in WHERE clause.

**Comment by darold** [comment] 2017-02-03 14:15
Ora2Pg create the function as volatile if the function is not declared as DETERMINISTIC in Oracle.

The problem is that we don't know if the function will modify or not the db, it can call insert/update/delete or any other function that it is writting in the db.

**Comment by okbob** [comment] 2017-02-03 15:57
What I know - the Oracle functions cannot to modify database. It is allowed only in Pg

**Comment by darold** [comment] 2017-02-03 20:49
Oh ok, function not procedure, I understand now. As Pg only support function, Ora2Pg convert both DDLs into a function, but yes I can keep that information and change default to STABLE when the code is converted from a function.

**Comment by darold** [comment] 2017-02-03 23:17
Commit 30592d5 force function to be exported as stable.

**Comment by okbob** [comment] 2017-02-04 05:44
It doesn't work for some cases:
PL/SQL:
<pre>
function CHAR_TO_DATE( mdatum IN CHAR  )
return DATE
is
begin
  return( TO_DATE( mDatum , 'DD.MM.YYYY' ));
end ;
</pre>

Ora2pg result
<pre>
CREATE OR REPLACE FUNCTION char_to_date ( mdatum CHAR ) RETURNS date AS $body$                                                                                                                                                                
BEGIN                                                                                                                                                                                                                                         
  return( TO_DATE( mDatum , 'DD.MM.YYYY' ));                                                                                                                                                                                                  
end                                                                                                                                                                                                                                           
$body$                                                                                                                                                                                                                                        
LANGUAGE PLPGSQL                                                                                                                                                                                                                              
SECURITY DEFINER                                                                                                                                                                                                                              
;   
</pre>

**Comment by darold** [comment] 2017-02-04 08:03
Sorry, case sensitivity issue again, might be fixed by commit  e467f65

**Comment by okbob** [comment] 2017-02-05 09:54
it is fixed

**Closed** 2017-02-05 14:50 UTC
