### ISSUE TITLE
Missing `PERFORM` before procedure call

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#394] opened 2017-05-03 12:29 UTC
Oracle:
<pre>
CREATE OR REPLACE procedure IDES_JMMAJ.REKONSTRUKCE_PLOCH_PRSTR_ALL( mWhere IN VARCHAR2 , mTransakce IN CHAR , mLIDENT  IN NUMBER ) is
  TYPE TqProstory IS REF CURSOR;
  qProstory TqProstory;
  mSQLProstory VARCHAR2( 4000 );
  mID_PROSTOR OBPPRSTR.ID_PROSTOR%TYPE;

begin
  
   IF mWhere IS NOT NULL THEN
     mSQLProstory := ' SELECT ID_PROSTOR FROM V_OBPPRSTR MT WHERE ' || mWhere  ;
   ELSE
     mSQLProstory := ' SELECT ID_PROSTOR FROM V_OBPPRSTR WHERE ID_PROSTOR = -1 ' ;
   END IF;
   OPEN qProstory FOR mSQLProstory ;
   LOOP
      FETCH qProstory INTO mID_PROSTOR ;
      EXIT WHEN qProstory%NOTFOUND;
   
      REKONSTRUKCE_PLOCH( NULL , mID_PROSTOR , NULL , 'A' );
   
   END LOOP;
 

  
end REKONSTRUKCE_PLOCH_PRSTR_ALL;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION ides_procs.rekonstrukce_ploch_prstr_all(mwhere text, mtransakce character, mlident numeric)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE

  qProstory REFCURSOR;
  mSQLProstory varchar(4000 );
  mID_PROSTOR OBPPRSTR.ID_PROSTOR%TYPE;

BEGIN

   IF mWhere IS NOT NULL THEN
     mSQLProstory := ' SELECT ID_PROSTOR FROM V_OBPPRSTR MT WHERE ' || mWhere;
   ELSE
     mSQLProstory := ' SELECT ID_PROSTOR FROM V_OBPPRSTR WHERE ID_PROSTOR = -1 ';
   END IF;
   OPEN qProstory FOR EXECUTE mSQLProstory;
   LOOP
      FETCH qProstory INTO mID_PROSTOR;
      IF NOT FOUND THEN EXIT; END IF; -- apply on qProstory

      REKONSTRUKCE_PLOCH( NULL , mID_PROSTOR , NULL , 'A' );

   END LOOP;

  
END;
$function$
</pre>

Note: PLpgSQL has `EXIT WHEN` statement. So this case can be translated to `EXIT WHEN NOT FOUND`

**Comment by darold** [comment] 2017-05-04 14:01
Commit cabcb9a fix the translation of `EXIT WHEN cursor%NOTFOUN` statement but I'm not able to reproduce the function call replacement. Maybe it has already been fixed in a previous commit.

**Comment by darold** [comment] 2017-05-04 14:03
Errata: I can reproduce the issue.

**Comment by darold** [comment] 2017-05-04 14:41
Commit a16e57f fixes the missing PERFORM replacement issue.

**Comment by okbob** [comment] 2017-05-04 17:30
yes. This issue is fixed. Thank you

**Closed** 2017-05-05 07:52 UTC
