### ISSUE TITLE
Wrong translation of NVL2 functions

### ISSUE THREAD

**Issue by beaud76** [darold/ora2pg#809] opened 2019-08-08 09:03 UTC
NVL2 function are currently translated as COALESCE. The instruction:
$str =~ s/NVL2\s*\($field,$field,$field\)/coalesce($1,$3)/is;
is coded twice in PLSQL.pm.
The right translation should probably be something like :
$str =~ s/NVL2\s*\($field,$field,$field\)/CASE WHEN $1 IS NOT NULL THEN $2 ELSE $3 END/is;

**Comment by darold** [comment] 2019-08-08 09:33
Hi Philippe,

This is a duplicate of #789 unfortunately I don't have time to work on it and lot of other issues for the moment, I hope that October will give me more spare time.

**Comment by beaud76** [comment] 2019-08-08 09:50
Hi Gilles,
Ah sorry, I should have checked the existing issues. :-/
No problem for me regarding the delay.
Hang in there! ;-)

**Comment by darold** [comment] 2020-09-18 13:57
Fixed with commit 0f4a86b.

**Closed by darold** 2020-09-18 13:57 UTC
