### ISSUE TITLE
Function and Procedures migration is too slow

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#357] opened 2017-04-01 04:31 UTC
Last changes in ora2pg did very significant slowdown of migration.

**Comment by darold** [comment] 2017-04-02 16:38
Please use latest development code, commit 81339c1 aggregate call on comment and text constant replacement, this might improve migration speed.

If this is not the case or still too slow please send to my private email the DDL export of the database your are migrating or the specific objects that are slow to migrate. I will run the perl profiler to find the code responsible of the speed lost and perhaps anticipate some other issues.

**Comment by okbob** [comment] 2017-04-03 15:08
The speed is same - I'll ask my customer about sending DDL

**Comment by darold** [comment] 2017-04-03 16:00
OK, note that the DDL code can be anonymized provide that it can be imported even if it is marked as invalid by Oracle.

**Comment by okbob** [comment] 2017-04-05 15:43
[nytprof.tar.gz](https://github.com/darold/ora2pg/files/899964/nytprof.tar.gz)
I am sending a report from NYTPerf

**Comment by darold** [comment] 2017-04-14 21:30
Commit 07f8fc3 might save some performances lost but this is not the slowest part. The main performances lost are in function plsql_to_plpgsql() while rewriting direct call to function without out parameters using PERFORM.

Does the profiling is the result of just the call to ora2pg on the FUNCTION export type?

**Comment by darold** [comment] 2017-04-17 16:02
In the profiling most of the time is spent in Ora2Pg::PLSQL::plsql_to_plpgsql() function and especially in the  code to append PERFORM before a function call when needed. As you have more than a thousand of function Ora2Pg is looking in each function if one or more of the thousand other function are called inside the current code, which mean more that one million of loop. And as Ora2Pg is doing that on the declare and code section, this represent more than two millions of iteration.

To improve performances I have merged the two call for declare and code section into a single one, which might divide by two the time passed in this part. Commit 8a45f08 is responsible of this change.

An other performances gain might be done by commit 989e487 which merge two slow regexp into a single one. This could lead to also divide by two the time passed in this part. That mean that the time saved by these improvements must be around 3 to 4 time.

Please send me a new NYTPerf with these changes to see where other improvement can be done.

Regards,

**Comment by okbob** [comment] 2017-04-17 16:23
yes, there are more than thousands functions - the code has about 45K lines of functions and 250K lines of procedures. Now there are running the procedures migration. When it will be done, I'll do new profile report.

**Comment by okbob** [comment] 2017-04-17 16:25
Can be this export paralelized? The only one CPU is utilized. We are do migration from database to file.

**Comment by darold** [comment] 2017-04-17 16:28
Yes it should be paralelized, I will think about that.

**Comment by darold** [comment] 2017-04-17 17:44
Commit 8a45f08 was not correct, might be fixed with new commit 63d8c4d

**Comment by darold** [comment] 2017-04-18 19:50
With last commit 7f950b1 it is now possible to use -j or JOBS in ora2pg.conf to parallelyze FUNCTION and PROCEDURE export.  It need additional work on PACKAGE export. Let me know about performances too.

**Comment by okbob** [comment] 2017-04-19 18:34
The speedup without jobs are not strong - using more jobs helps significantly

**Comment by okbob** [comment] 2017-04-20 04:35
new perf report 
[nytprof.tar.gz](https://github.com/darold/ora2pg/files/940321/nytprof.tar.gz)

**Comment by darold** [comment] 2017-04-20 11:57
Thanks for the new profiling. I've reverted the patch that merged the two regexp to append PERFORM in IF block into a single regex. After studying the last NytProf report it seems that a single regex is slowest than the two original regexp calls.

The two calls:
```
$str =~ s/(IF(?:(?!CASE).)*?THEN)((?:\s*%ORA2PG_COMMENT\d+\%\s*)*\s*)($k\s*[\(;])/...
$str =~ s/(IF(?:(?!CASE).)*?ELSE)((?:\s*%ORA2PG_COMMENT\d+\%\s*)*\s*)($k\s*[\(;])...
```
tooks a sum of 2.5ms/call and the single one regex:
``` 
$str =~ s/(IF(?:(?!CASE).)*?(?:THEN|ELSE))((?:\s*%ORA2PG_COMMENT\d+\%\s*)*\s*)($k\s*[\(;])/...
```
take an average of 3.56ms/call in your last NytProf report.

Commit 0b36f55 recover the split into two regexp.

**Comment by okbob** [comment] 2017-04-21 17:11
Paralel procedure processing doesn't work. Minimally last stage - when temp files are copied to target place. The result of export is only few initial lines.

**Comment by darold** [comment] 2017-04-21 17:48
Parallel procedure export doesn't create temporary file, each procedures are directly written to a dedicated file (FILE_PER_FUNCTION is forced). Using `ora2pg -p -c config/ora2pg.conf -t PROCEDURE -b tmp/  -j 2` I'm not able to reproduce the issue. Maybe you need to pull latest developement code, last commit must be ee05bdf

**Comment by okbob** [comment] 2017-04-21 18:06
I'll recheck it again - now, it is faster - only 22 hours.
Note: trigger translation doesn't support jobs.

**Comment by darold** [comment] 2017-04-21 18:19
I will work on triggers parallel export asap, still traveling right now. Can you precise what is taking 22 hours, is this only the procedure/function/package export or the full migration with data export?

**Comment by darold** [comment] 2017-04-21 22:06
Ok, I've created a thousand of functions to better understand the problem. To begin last commit 9e90afb might save lot of time being wasted trying to replace function when it is not called in the current code.

**Comment by okbob** [comment] 2017-04-22 05:54
FILE_PER_FUNCTION is working.
Is possible to have one file only? Or N procedures/functions in file?

**Comment by okbob** [comment] 2017-04-22 05:59
Is possible to print the translation time. I have subjective feeling, so translation is slower and slower in time.

**Comment by darold** [comment] 2017-04-22 06:36
In parallel mode it is not possible to have all functions in a single file. I will fully rewrite the parallelism on function export. The actual code, forks a new process for each function, I will regroup a certain amount of functions per process to save some resources.

**Comment by okbob** [comment] 2017-04-23 17:00
Some is pretty strange - a export of all procedures is running more than 22 hours with more jobs. But if I run export one by one with following script - the complete export is done in 30 minutes.
<pre>
while read name; do echo "$name"; time tom_ora2pg -t PROCEDURE -o ./procs/$name.sql --temp_dir ./proceduretmp -a $name; done < procedures
</pre>

**Comment by darold** [comment] 2017-04-23 22:00
Yes I have rewritten most of the multiprocess code and also the way Ora2Pg is first looking for the functions and procedures metadata in the Oracle database to look for replacement of function with OUT parameters. Last commit d291384 might solve these performances issues but there's still some works on progress bar and other export types (triggers and package).

**Comment by okbob** [comment] 2017-04-24 09:56
Last version is very fast - but produces broken result. End of functions looks bad:
<pre>
  END IF;                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                               
END;                                                                                                                                                                                                                                           
FUNCTION TVORBA_VYRPOD_ODECTY( mID_VYROK VYROK.ID_VYROK%TYPE , mID_ODBMISTO OBPODBMI.ID_ODBMISTO%TYPE ,                                                                                                                                        
                            mLIDENT IN NUMBER , mPLATNOST_OD IN VYROK.PLATNOST_OD%TYPE , mOd_vyu_VSTUP IN VYROK.ODVYU%TYPE , mDo_vyu_VSTUP IN VYROK.DOVYU%TYPE ,  mID_SKUTPRS IN OBPPRSTR.ID_SKUTPRS%TYPE ,                                    
                            mZPPROVEDENI IN CHAR , mPocChyb IN NUMBER , mNEPRE_VYMENA_MERIDEL IN CHAR ) is                                                                                                                                     
  A CHAR(1);                                                                                                                                                                                                                                   
  mID_VYRPODPRSTR_NEW VYRPODPRSTR.ID_VYRPODPRSTR%TYPE;  
</pre>
or
<pre>
   END LOOP;                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                               
END;                                                                                                                                                                                                                                           
FUNCTION SELECT * FROM VRACENI_PENEZ_ABO_ALL(mSelect IN VARCHAR2 , mWhere IN VARCHAR2 ,                                                                                                                                                        
 mEVRATIT IN NUMBER , mLIDENT IN NUMBER  ,                                                                                                                                                                                                     
 mTransakce IN CHAR  , mTvorba_platby IN CHAR  ,                                                                                                                                                                                               
 mUCE_DOKLAD_VSTUP IN NAJPLATBY.UCE_DOKLAD%TYPE,                                                                                                                                                                                               
 mUCE_DOKLAD_CISLO IN NAJPLATBY.UCE_DOKLAD_CISLO%TYPE,                                                                                                                                                                                         
 mID_CISDRUPLAT IN OUT  CISDRUPLAT.ID_CISDRUPLAT%TYPE  ,                                                                                                                                                                                       
 mID_DPLA IN OUT CISDPLAT.ID_DPLA%TYPE , mDatum_Vraceni  IN DATE ,                                                                                                                                                                             
 mID_PARBUSTAV PARBUSTAV.ID_PARBUSTAV%TYPE , mTYP_SLOUCENI IN CHAR ) INTO mID_CISDRUPLAT IN OUT  CISDRUPLAT.ID_CISDRUPLAT%TYPE,mID_DPLA IN OUT CISDPLAT.ID_DPLA%TYPE is                                                                        
                                                                                                                                                                                                                                               
 TYPE TqNajplatby REFCURSOR;                                                                                                                                                                                                                   
 qNajplatby TqNajplatby;                                                                                                                                                                                                                       
</pre>

**Comment by darold** [comment] 2017-04-26 14:25
Hi Pavel,

Sorry for the reponse delay, Ora2Pg development and support fallback to my spare time only so some lag can appear. I think this issue might be fixed with last development code, especially with commit  bf626cc.

If that's not fixed please check if there is a function declared in an other function, this is know to break the parser. With PL/PSQL it is possible to call a CREATE FUNCTION statement inside a function, it need to be extracted and created outside the function in Oracle before export.

**Comment by okbob** [comment] 2017-04-26 16:10
No sorry :) - your work is big help for us. 

I am sure so original code doesn't use nested functions or nested CREATE FUNCTION statement, 

I'll check last commit immediately

**Comment by okbob** [comment] 2017-04-27 02:14
It is broken still :(

**Comment by okbob** [comment] 2017-04-30 07:41
This issue can be closed - now, the procedure exports needs about 100 min, what is acceptable (and much better than 4 days) :)

**Comment by darold** [comment] 2017-04-30 08:42
Good news :-)

**Closed by darold** 2017-04-30 08:42 UTC
