### ISSUE TITLE
When column name is Chinese，the config MODIFY_TYPE does not work

### ISSUE THREAD

**Issue by Code-UV** [darold/ora2pg#1290] opened 2021-11-17 10:04 UTC
I have a table whose column names are in Chinese. 
When I configure "MODIFY_TYPE STUDENT:名字:varchar(255)", (名字 is name in Chinese)，I found that it has no effect. 
When I debug, I found that read_config() is not utf8 encoding when reading the configuration file, which caused this exception.

**Comment by darold** [comment] 2021-11-17 10:37
Good catch I will fix it.

**Comment by darold** [comment] 2021-12-01 10:32
Unfortunately I can not reproduce the issue because sqlplus creates the column name with ??? instead of the chinese column name. I don't know which system local en environment variable configuration I should use to be able to create such object name in chinese.

**Comment by Code-UV** [comment] 2021-12-03 06:35
Maybe you can use DOCKER to deploy  oracle. Then connect it through Navicat to create a database with utf8 or GBK character set

**Comment by darold** [comment] 2021-12-05 04:20
I already have a database with utf8 and there is no issues, I think that the problem is related to the locale but I can try to set NLS_CHAR to GBK to see what happen.

**Comment by darold** [comment] 2022-07-10 08:59
Commit 34b229c force reading the configuration file using utf8. I don't know if it can solve this issue but this is the less I can do without being able to reproduce the issue. Closing.

**Closed by darold** 2022-07-10 08:59 UTC
