### ISSUE TITLE
ORA-03114 error on latest versions of ora2pg

### ISSUE THREAD

**Issue by janteque** [darold/ora2pg#1532] opened 2022-10-26 15:35 UTC
I'm trying to execute ora2pg from a docker container against a remote Oracle 10g database through a VPN.

I could test the connection and even generate the report without problems.

`ora2pg -t SHOW_REPORT`

However, while executing the schema export I was receving this error

`FATAL: ORA-03114: not connected to ORACLE (DBD ERROR: OCIStmtExecute/Describe)
Aborting export...`

I found this issue https://github.com/darold/ora2pg/issues/634 with exactly the same problem and, as in here, once I downgraded ora2pg version to 17.4 it worked perfectly.

**Comment by gilles-migops** [comment] 2022-10-27 13:40
Well unless the problem is reproducible with others VM systems or directly on a Linux host I can not help much more on this issue, I'm not a specialist of docker.

**Comment by janteque** [comment] 2022-10-31 15:12
Thanks gilles, 

I've installed ora2pg on a Ubuntu (without docker) and the problem is still there.

The funny thing is that not all the commands fail:

These commands fail:
ora2pg -t SHOW_TABLE 
ora2pg -t SHOW_COLUMN
ora2pg -p -t TABLE

While these ones work:

ora2pg -t SHOW_TABLE 
ora2pg -p -t VIEW
ora2pg -p -t SEQUENCE

I'm a bit clueless here.

What kind of information should I provide to help ifentifying the root cause?

**Comment by darold** [comment] 2022-10-31 16:04
Please provide the output of command `ora2pg -p -t TABLE -d` with the error if any, the `-d` switch will enable the debug output.

**Comment by janteque** [comment] 2022-11-02 13:01
This is the output I get:
```
[2022-11-02 13:04:49] Ora2Pg version: 23.2
[2022-11-02 13:04:49] Export type: TABLE
[2022-11-02 13:04:49] Geometry export type: INTERNAL
[2022-11-02 13:04:49] ORACLE_HOME = /usr/lib/oracle/12.2/client64/
[2022-11-02 13:04:49] NLS_LANG = AMERICAN_AMERICA.AL32UTF8
[2022-11-02 13:04:49] NLS_NCHAR = AL32UTF8
[2022-11-02 13:04:49] Trying to connect to database: dbi:Oracle:host=##############;sid=#######;port=50599
[2022-11-02 13:04:51] Isolation level: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
[2022-11-02 13:04:51] Force Oracle to compile schema GESO before code extraction
[2022-11-02 13:04:52] Looking forward functions declaration in schema GESO.
[2022-11-02 13:04:56] Retrieving table information...
[2022-11-02 13:05:07] FATAL: ORA-03113: end-of-file on communication channel
Process ID: 0
Session ID: 1368 Serial number: 45967 (DBD ERROR: OCIStmtExecute/Describe)
Aborting export...
```

**Comment by darold** [comment] 2022-11-15 09:44
There is a client/server communication problem. Does you Oracle server have enough resources or a network timeout has closed the connection?

**Comment by janteque** [comment] 2022-11-17 14:19
It must have as when I use version 17.4 of ora2pg everithing works fine. I only got this error with version 17.5 upwards

**Comment by janteque** [comment] 2022-11-17 16:49
I tried with docker and with Ubuntu. Same result

**Comment by darold** [comment] 2022-11-19 18:02
Well I can not help much more with this issue without access to the host, something is closing the connection.

**Closed by darold** 2022-11-19 18:02 UTC
