### ISSUE TITLE
nytprof profile of our PL/SQL transformation

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#479] opened 2017-06-28 10:08 UTC
Our procedures translation is running about 2 hours. It is acceptable, but can be nice to be faster. The most slow part is _restore_text_constant_part. See attached profile
[nytprof.tar.gz](https://github.com/darold/ora2pg/files/1108275/nytprof.tar.gz)

**Comment by darold** [comment] 2017-08-31 13:32
I have removed a probable useless call of _restore_text_constant_part() in commit 9248200, at least in my regression tests it seem useless. To be sure that it is useless you can execute the following command: `grep -ri "TEXTVALUE" path_to_all_function/` if something is found that means that the commit need to be reverted.

If you have the opportunity to run an other time NYTProf please attach the result it here. Thanks in advance.

**Comment by okbob** [comment] 2017-08-31 14:03
Dne 31. 8. 2017 15:32 napsal uživatel "Gilles Darold" <
notifications@github.com>:

I have removed a probable useless call of _restore_text_constant_part() in
commit 9248200
<https://github.com/darold/ora2pg/commit/9248200e176c41af0b0f8d43324114986cfaca38>,
at least in my regression tests it seem useless. To be sure that it is
useless you can execute the following command: grep -ri "TEXTVALUE"
path_to_all_function/ if something is found that means that the commit need
to be reverted.

I don't understand what means "path-to-all-function"


If you have the opportunity to run an other time NYTProf please attach the
result it here. Thanks in advance.


I run profiler at evening

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/darold/ora2pg/issues/479#issuecomment-326296176>, or mute
the thread

**Comment by darold** [comment] 2017-08-31 16:27
> I don't understand what means "path-to-all-function"

This is where ora2pg has dumped your procedures/functions/packages to look in all .sql files if the pattern can be found.

**Comment by okbob** [comment] 2017-09-01 18:19
I don't see any string "TEXTVALUE" in translated code.

**Comment by okbob** [comment] 2017-09-01 18:25
new profile attached
[nytprof2.zip](https://github.com/darold/ora2pg/files/1271156/nytprof2.zip)

**Comment by okbob** [comment] 2017-09-01 20:36
last changes helped - the migration of our procedures needs 120 minutes - week ago it required 150 minutes, but two weeks ago only about 100 minutes.

**Comment by darold** [comment] 2017-09-01 21:12
Yes, for what I see most of the time is lost in sub _restore_text_constant_part() and especially in the inner loop where it try to prefix functions with their package (schema) name in the dynamic queries strings.

I can add a test before call to map (where most of time is lost) to not go through this call if the function name is not found at all string. This test will have a cost but probably less that the substitution done in the  call to map.

**Comment by darold** [comment] 2017-09-01 21:43
No it don't help at all, at least on my small number of function. I think that the only way to improve speed of this part is call it a single time, the problem is the number of iteration. This is possible by keeping all function and strings in memory and to write translated code to file at end, not each time a function is translated. I will make a try later.

**Comment by okbob** [comment] 2017-09-02 03:54
2017-09-01 23:43 GMT+02:00 Gilles Darold <notifications@github.com>:

> No it don't help at all, at least on my small number of function. I think
> that the only way to improve speed of this part is call it a single time,
> the problem is the number of iteration. This is possible by keeping all
> function and strings in memory and to write translated code to file at end,
> not each time a function is translated. I will make a try later.
>
Postgres has for this purpose lot of session system caches - it doesn't do
prefetch from system catalogue, but any info about function, table, column
is read, and processed from system catalogue only one times per session.

For example - Ora2pg every time parse function parameters - these data
should be cached well.

Sure - the benefits of caching is better visible on large set of procedures
- we have about 0.25 M rows.

**Comment by darold** [comment] 2017-12-08 23:59
I have completely rewritten the part that caused most of the performances lost with the last two commit bd3f5f3 and 06d7010. Now the call to function normalize_function_call() used to requalify call to `
package.function()` in the translated code is done only once after all the output file have been written. The are reedited by Ora2Pg to requalify the call to function when necessary. 

On my computer a package export that takes 40 minutes with the old version now takes less than 4 minutes. Next step is to try to move the PERFORM replacement at end just like the requalification.

There is some other fixes too in these commit.

**Comment by okbob** [comment] 2017-12-09 08:09
The first steps looks faster, but second looks long - now one hour I see
<pre>
Translating of 1080 functions took: 6108 wallclock secs (6064.64 usr + 33.77 sys = 6098.41 CPU)
Total time to translate all functions with 1 process: 6108 wallclock secs (6064.66 usr + 33.80 sys = 6098.46 CPU)
Fixing function call in output files...
</pre>

**Comment by darold** [comment] 2017-12-09 09:24
Yes this is clearly the part that was taking the most time following your nytprof report. The good news is that this part is only executed one time :-) If you think that the function call are most of the time well qualified with `package_name.function_name` I can add a configuration directive to disable this second pass.

**Comment by okbob** [comment] 2017-12-09 11:29
2017-12-09 10:24 GMT+01:00 Gilles Darold <notifications@github.com>:

> Yes this is clearly the part that was taking the most time following your
> nytprof report. The good news is that this part is only executed one time
> :-) If you think that the function call are most of the time well qualified
> with package_name.function_name I can add a configuration directive to
> disable this second pass.
>
in my case, yes - but nobody can ensure it.

Now, the second pass is maybe slower than before - migration is running 366
minutes and still not finish.

I'll send a updated nytprof report

Pavel

**Comment by okbob** [comment] 2017-12-10 16:57
the second stage is running more than one day and result data file is not changed.

**Comment by darold** [comment] 2017-12-11 09:38
Well my bad I have forgotten to apply multiprocess on the second pass, it has been fixed in commit e85eefd.

**Comment by darold** [comment] 2017-12-11 10:52
Commit ae1dfa9 also exclude functions and procedures that do not need to be qualified.

**Comment by darold** [comment] 2017-12-11 15:08
Hi Pavel,

I had some discussion with @edelanoe and he point me how stupid was my implementation of the function qualification process.  Last commit f1166e5 might solve the performances issues, the second pass is now only use to re-qualify calls to pkgname.fctname into pkgname_ftcname when PACKAGE_AS_SCHEMA is disable. This mean that by default Ora2Pg will not go through the second pass. Note that if you have function with non supported character or you have enabled PRESERVE_CASE there will be no more change on function call, this takes too much time to process.

I'm travelling so I don't have my test database with me to confirm the performances gain but I'm confident that the current development code is far more efficient. I have also remove QUALIFY_FUNCTION configuration directive, there is no more reason to use it.

Sorry for the inconvenient with the previous implementation. Let me know if that's change something in the translation output.

**Comment by okbob** [comment] 2017-12-12 13:19
I have not any problem so sometimes ora2pg is slow - it is life  - progress is joined with bugs :) - and I am very happy so it has significant progress. I am happy so I can say, so last commit fixed performance problems - now our procedure transformations needs 100 min and functions are translated after 10 mins. Thank you.

**Comment by okbob** [comment] 2017-12-13 06:08
Updated profile 
[nytprof1.zip](https://github.com/darold/ora2pg/files/1554279/nytprof1.zip)

**Closed** 2018-08-16 22:03 UTC
