### ISSUE TITLE
Not getting the result by running procedure command in Linux env

### ISSUE THREAD

**Issue by Saurabh-704** [darold/ora2pg#925] opened 2020-07-26 05:13 UTC
Hello Darold!!
I am trying to create a script  in Linux for procedure by running the command-
"ora2pg -t PROCEDURE -c ora2pg1.conf -o procedure2.sql"
But it seems to be stuck, because from last 1 hour its running and nothing is happening, means no output is coming.
I will also attach screenshot with this for your reference.
Can you please help me with this issue?
Thanks in Advance!!
<img width="505" alt="linux" src="https://user-images.githubusercontent.com/47383623/88472023-c642d200-cf2c-11ea-90f2-9e2444233ed7.png">

**Comment by darold** [comment] 2020-07-26 06:13
This is a duplicate of #924, I don't know what happen and can not reproduce it. Try the solution given in the last note, if you see that ora2pg is hanging when parsing the DDL file let me know.

**Closed** 2020-07-30 10:26 UTC
