### ISSUE TITLE
Problems with varchar2 size overflow - import data directly

### ISSUE THREAD

**Issue by bcosso** [darold/ora2pg#183] opened 2016-04-12 16:49 UTC
Hi, we have been having some problems when importing data directly from Ora2pg (instead of generate insert commands. The insert commands runs normally when executed manually in pgAdmin. 
An overflow is happening when we insert with the E'data'. We already turned off standard_conforming_strings settings but didn't work. The inserted field, when not overflowed, inserts the entire "  E'data' ", instead of "data" only, that's why is overflowing.
I have created a workaround (I am not really a Perl developer) that worked for us so far, but hopefully you will find a better solution.
I added to format_data_row function this code before the closing main "for" brackets:

`		######################################################################################
		#Changes due to migration errors of Null fields and characters like "E'", "'" and "\\"
		if ($row->[$idx] && $src_data_types->[$idx] =~ /(VARCHAR2|char|text|xml)/i){
			$self->logit('\r\n Is character Type:' . $row->[$idx] , 1);
			
			while (index($row->[$idx], "'") != -1){
				$row->[$idx] = str_replace("'", "", $row->[$idx]);
			}
			
			while (index($row->[$idx], "\\\\") != -1){
				$row->[$idx] = str_replace("\\\\", "\\", $row->[$idx]);
			}
		}
		if ($row->[$idx] eq "null" || $row->[$idx] eq "NULL"){
			$self->logit('\r\n Result Null Type:' . $src_data_types->[$idx] , 1);
			$row->[$idx] = undef;
		}
		
		$self->logit('\r\n Contents:' . $row->[$idx] . '--', 1);
		#######################################################################################`

And also used the following function for replace:

`sub str_replace {
	my $replace_this = shift;
	my $with_this  = shift; 
	my $string   = shift;
	
	my $length = length($string);
	my $target = length($replace_this);
	
	for(my $i=0; $i<$length - $target + 1; $i++) {
		if(substr($string,$i,$target) eq $replace_this) {
			$string = substr($string,0,$i) . $with_this . substr($string,$i+$target);
			return $string; #Comment this if you what a global replace
		}
	}
	return $string;
}

`

[Ora2Pg.pm.txt](https://github.com/darold/ora2pg/files/215500/Ora2Pg.pm.txt)

**Comment by darold** [comment] 2016-04-12 17:32
There was bug in previous and current release when exporting data. If you use latest development code you may not have to fix anything. Please use COPY export type as INSERT is only given for convenience and it is really slow.

Let us know.

**Comment by bcosso** [comment] 2016-04-14 16:57
Thank you very much for your quick reply.

We had it tested also in version 17.3 and the problem remains the same. The development team running the tests used that code in the new version for INSERT mode to work and avoid the overflow issue. They are still testing COPY mode, so I will have to wait their results. Thanks again for your help.

**Comment by darold** [comment] 2016-04-22 19:21
Version 17.4 have been published, please give it a try and let me know if your still have the issue.

**Comment by darold** [comment] 2016-04-26 20:40
I'm closing this issue because it is not reproducible.

**Closed by darold** 2016-04-26 20:40 UTC
