### ISSUE TITLE
Export materialized views as tables

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [darold/ora2pg#1217] opened 2021-07-26 11:30 UTC
hey,
there is any way to export a snapshot of materialized views as tables together with data loading?

I tried with REPLACE_QUERY and VIEW_AS_TABLE but none work with mviews

**Comment by darold** [comment] 2021-10-05 20:40
No way for the moment. Closing this is a duplicate of #1216

**Closed by darold** 2021-10-05 20:40 UTC
