### ISSUE TITLE
Ora2Pg v19.0. Export composite partitioned (range/hash) table from Oracle 11.2.0.4 into Postgresql 10 

### ISSUE THREAD

**Issue by denoley** [darold/ora2pg#678] opened 2018-08-21 14:36 UTC
There is a table In Oracle:
`
CREATE TABLE KBLN_INFO
(  
  BLANK_NUMBER_INT            NUMBER,
  BLANK_SERIES                VARCHAR2(50 CHAR),
  ...
)
PARTITION BY RANGE (BLANK_NUMBER_INT)
INTERVAL( 500000)
SUBPARTITION BY HASH (BLANK_SERIES)
`

Ora2pg generate instructions in table.sql:
`CREATE TABLE kbln_info (...);`
and in partition.sql:
`CREATE TABLE p0_sys_subp11395 ( CHECK (
	BLANK_NUMBER_INT < 500000 AND 
) ) INHERITS (KBLN_INFO);`

As you see, after AND in partition.sql there is an empty space. So, when script execute, i have an error:
`ERROR:  syntax error at or near ")"
LINE 3: ) ) INHERITS (KBLN_INFO);
        ^
SQL state: 42601
Character: 73`

**Comment by denoley** [comment] 2018-08-22 06:53
Previous version of Ora2Pg (18.2) ignored hash-partitions/subpartitions, so composite-partitioned tables could be exported (exported only range partitions), and in our project is enougth. But in v.19.0 there is no oportunities to export such tables into postgres. Workaround - switch of partitions, but it isn't good idea.

**Comment by darold** [comment] 2018-08-22 08:45
If you have a PostgtreSQL version >= 10.0 you have to enable PG_SUPPORTS_PARTITION in ora2pg.conf to use the native partitioning. Here it is exported using the old partitioning based on inheritance.

However it looks like the problem comes from the `INTERVAL( 500000)` which is not supported. I will try to fix that.

Thanks for the report.

**Comment by denoley** [comment] 2018-08-22 08:53
I'm runing 
PostgreSQL 10.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit

When i set PG_SUPPORTS_PARTITION = 1, ora2pg generates constructions, which can't executed in psql.
So, i'm rollback vrsion to 18.2 This version generates well-working construction:

```
CREATE TABLE sys_p11928 ( CHECK (
	BLANK_NUMBER_INT >= 500000 AND BLANK_NUMBER_INT < 1000000
) ) INHERITS (KBLN_INFO);

```

**Comment by darold** [comment] 2018-08-22 08:56
Yes but enabling PG_SUPPORTS_PARTITION with 18.2 should works too with native partitioning. You will not have HASH partition too.

**Comment by darold** [comment] 2018-08-22 09:44
With 19.0 and PG_SUPPORTS_PARTITION enable it looks good for me now after a typo fixed in commit 3b52266 and a fix in MODULUS value in commit a79b7d1).  Here is a sample of export:

```
CREATE TABLE subpartsales (
        prod_id integer,
        cust_id bigint,
        time_id timestamp,
        channel_id char(1),
        promo_id integer,
        quantity_sold smallint,
        amount_sold double precision
) PARTITION BY RANGE (prod_id) ;

CREATE TABLE subpartsales_1 PARTITION OF subpartsales
FOR VALUES FROM (MINVALUE) TO (500000)
PARTITION BY HASH (cust_id);
CREATE TABLE subpartsales_1_sys_subp758 PARTITION OF subpartsales_1
FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE subpartsales_1_sys_subp759 PARTITION OF subpartsales_1
FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE subpartsales_1_sys_subp760 PARTITION OF subpartsales_1
FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE subpartsales_1_sys_subp761 PARTITION OF subpartsales_1
FOR VALUES WITH (MODULUS 4, REMAINDER 3);
```

This will works with PostgreSQL 11, if you want to use v10 you will have to remove the lines concerning hash partitioning. I will look to inheritance partitioning export.

**Comment by denoley** [comment] 2018-08-22 09:49
If i'll remove hash-partitioned lines, will data export `ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf` execute successfully?

**Comment by darold** [comment] 2018-08-22 09:54
Yes when PG_SUPPORTS_PARTITION is enable, the DISABLE_PARTITION configuration directive is also enabled with data export. This prevent Ora2Pg to perform a direct import into each partition that is mandatory with inheritance partitioning for performances reason.

**Comment by denoley** [comment] 2018-08-22 10:01
In this case, table with, for example, 1000 partitions with 100K records in each,  will be export sequentially, not parallel, when each oracle partition export in its own process?
Or i'm wrong?

**Comment by darold** [comment] 2018-08-22 10:17
You are right, this should be fixed/improved.

**Comment by denoley** [comment] 2018-08-22 11:27
I'm propose decision for this situation. If PG_SUPPORTS_PARTITION is enable, the DISABLE_PARTITION stay disabled, but data insert into table at all. I.e instead of direct import of each partition:

```
insert into subpartsales_1 (...) --postgres partition
select ..
from subpartsales  partition(subpartsales_1) -- oracle partition
```

you should use construction:

```
insert into subpartsales (...) -- postgres table
select ..
from subpartsales  partition(subpartsales_1) -- oracle partition
```
This will parallelize the export of data from the oracle and the insertion it into postgresql (Postgresql will automatically determine which partition to put data in).

**Comment by darold** [comment] 2018-08-22 11:37
Yes this is also what I have in mind.

**Comment by darold** [comment] 2018-08-22 16:04
Commit 5f7cada might fix this issue.

**Comment by denoley** [comment] 2018-08-24 08:01
During export i've recieved error:
```
Aborting export...
Wide character in subroutine entry at /var/lib/pgsql/perl5/lib/perl5/Ora2Pg.pm line 13603.s/sec), KBLN_BLANK in progress.
DBD::Pg::db pg_putcopyend failed: ERROR:  no partition of relation "sys_p11588" found for row
DETAIL:  Partition key of the failing row contains (blank_series) = (ЕЕЕ).
CONTEXT:  COPY kbln_info, line 1: "2F1CF4BBAC97544EE053930C1    1       ЕЕЕ     0358684657      \N      3       1       2015-08-19 00:00:00     2016-03-28 16:33:42     0       0       \N      ..." at /var/lib/pgsql/perl5/lib/perl5/Ora2Pg.pm line 13603.
Wide character in print at /var/lib/pgsql/perl5/lib/perl5/Ora2Pg.pm line 12799.
FATAL: ERROR:  no partition of relation "sys_p11588" found for row
DETAIL:  Partition key of the failing row contains (blank_series) = (ЕЕЕ).
CONTEXT:  COPY kbln_info, line 1: "2F1CF4BBAC97544EE053930C1    1       ЕЕЕ     0358684657      \N      3       1       2015-08-19 00:00:00     2016-03-28 16:33:42     0       0       \N      ..."
DBD::Oracle::db disconnect failed: ORA-03135: connection lost contact
Process ID: 0
Session ID: 150 Serial number: 2739 (DBD ERROR: OCISessionEnd) at /var/lib/pgsql/perl5/lib/perl5/Ora2Pg.pm line 12811.

```
Is it Postgresql error, or Ora2Pg error?

**Comment by darold** [comment] 2018-08-24 08:51
Please use latest development code, this will help to have the right line number with current code.

Do you mean that if you turn DISABLE_PARTITION to 1 you do not reproduce the error? This force Ora2Pg to extract data from KBLN_INFO table (not from partition directly) and insert it into the same table in PostgreSQL without using direct import to partition.

Please post the output of command: `ora2pv -c config/ora2pg.conf -t SHOW_ENCODING`

**Comment by denoley** [comment] 2018-08-24 09:45
I found bug! Watch this:
Oracle DDL
```
CREATE TABLE KBLN_INFO  
 ( INFO_ID                     VARCHAR2(25 CHAR) DEFAULT substr(sys_guid(),1,25) NOT NULL,
  BLANK_TYPE_ID               VARCHAR2(7 CHAR),
  BLANK_SERIES                VARCHAR2(50 CHAR) NOT NULL,
  BLANK_NUMBER                VARCHAR2(50 CHAR) NOT NULL,
  CONTRACT_NUMBER             VARCHAR2(50 CHAR),
  ACC_SYSTEM_TYPE_ID          VARCHAR2(7 CHAR) 	NOT NULL,
  ACC_STATUS_ID               VARCHAR2(7 CHAR),
  ACC_STATUS_CHANGE_DATE      DATE 				NOT NULL,
  RECORD_DATE                 DATE				NOT NULL,
  BLANK_VERSION               NUMBER(5),
  REVOKE_REQUIRED             NUMBER(1)			NOT NULL,
  BRANCH_ID                   VARCHAR2(25 CHAR),
  PROCESS_STATUS_ID           VARCHAR2(7 CHAR),
  PROCESS_STATUS_CHANGE_DATE  DATE              DEFAULT SYSDATE NOT NULL,
  EXT_STATUS_ID               VARCHAR2(7 CHAR),
  EXT_STATUS_CHANGE_DATE      DATE,
  SIGN_HISTORICAL_DATA        NUMBER(1) 		NOT NULL,
  TRANSITION_ID               VARCHAR2(25 CHAR),
  BASE_INFO_ID                VARCHAR2(25 CHAR),
  SEND_FILE_NAME              VARCHAR2(100 CHAR),
  SEND_FILE_DATE              DATE,
  RESPONSE_FILE_NAME          VARCHAR2(100 CHAR),
  RESPONSE_FILE_DATE          DATE,
  HEAD_BRANCH_ID              VARCHAR2(25 CHAR),
  TUNNEL_ID                   VARCHAR2(25 CHAR),
  CONTRACT_ID                 VARCHAR2(50 CHAR),
  FOR_UPDATE_AGGREGATE_TABLE  NUMBER(1),
  COMPANY_ID                  VARCHAR2(8 CHAR),
  BLANK_NUMBER_INT            NUMBER Generated Always as (TO_NUMBER(BLANK_NUMBER)))	
	TABLESPACE &&bso_tspace_dat.	
	PARTITION BY RANGE (BLANK_NUMBER_INT) INTERVAL(500000) 
	SUBPARTITION BY HASH (BLANK_SERIES) subpartitions 4
		(PARTITION P0 VALUES LESS THAN (500000));
```


Ora2pg generate script:
```
CREATE TABLE kbln_info (
	info_id varchar(25) NOT NULL DEFAULT 'substr(uuid_generate_v4(),1,25)',
	blank_type_id varchar(7),
	blank_series varchar(50) NOT NULL,
	blank_number varchar(50) NOT NULL,
	contract_number varchar(50),
	acc_system_type_id varchar(7) NOT NULL,
	acc_status_id varchar(7),
	acc_status_change_date timestamp NOT NULL,
	record_date timestamp NOT NULL,
	blank_version integer,
	revoke_required smallint NOT NULL,
	branch_id varchar(25),
	process_status_id varchar(7),
	process_status_change_date timestamp NOT NULL DEFAULT LOCALTIMESTAMP,
	ext_status_id varchar(7),
	ext_status_change_date timestamp,
	sign_historical_data smallint NOT NULL,
	transition_id varchar(25),
	base_info_id varchar(25),
	send_file_name varchar(100),
	send_file_date timestamp,
	response_file_name varchar(100),
	response_file_date timestamp,
	head_branch_id varchar(25),
	tunnel_id varchar(25),
	contract_id varchar(50),
	for_update_aggregate_table smallint,
	company_id varchar(8),
	blank_number_int numeric
) PARTITION BY RANGE (blank_number_int) ;
...

CREATE TABLE p0 PARTITION OF kbln_info
FOR VALUES FROM (MINVALUE) TO (500000)
PARTITION BY HASH (blank_series);

CREATE TABLE p0_sys_subp11395 PARTITION OF p0
FOR VALUES WITH (MODULUS 262, REMAINDER 0);
CREATE TABLE p0_sys_subp11396 PARTITION OF p0
FOR VALUES WITH (MODULUS 262, REMAINDER 1);
CREATE TABLE p0_sys_subp11397 PARTITION OF p0
FOR VALUES WITH (MODULUS 262, REMAINDER 2);
CREATE TABLE p0_sys_subp11398 PARTITION OF p0
FOR VALUES WITH (MODULUS 262, REMAINDER 3);

CREATE TABLE sys_p11928 PARTITION OF kbln_info
FOR VALUES FROM (500000) TO (1000000)
PARTITION BY HASH (blank_series);

CREATE TABLE sys_p11928_sys_subp11924 PARTITION OF sys_p11928
FOR VALUES WITH (MODULUS 262, REMAINDER 0);
CREATE TABLE sys_p11928_sys_subp11925 PARTITION OF sys_p11928
FOR VALUES WITH (MODULUS 262, REMAINDER 1);
CREATE TABLE sys_p11928_sys_subp11926 PARTITION OF sys_p11928
FOR VALUES WITH (MODULUS 262, REMAINDER 2);
CREATE TABLE sys_p11928_sys_subp11927 PARTITION OF sys_p11928
FOR VALUES WITH (MODULUS 262, REMAINDER 3);
...

```

You have used MODULUS 262, but there are only 4 hash-subpartitions in every range partition. So, some records don't insreted into target table and i have an error: 

For example:
```
Insert into BSO_TEST2.KBLN_INFO
   (INFO_ID, BLANK_TYPE_ID, BLANK_SERIES, BLANK_NUMBER, ACC_SYSTEM_TYPE_ID, 
    ACC_STATUS_ID, ACC_STATUS_CHANGE_DATE, RECORD_DATE, BLANK_VERSION, REVOKE_REQUIRED, 
    PROCESS_STATUS_ID, PROCESS_STATUS_CHANGE_DATE, EXT_STATUS_ID, EXT_STATUS_CHANGE_DATE, SIGN_HISTORICAL_DATA, 
    RESPONSE_FILE_NAME, RESPONSE_FILE_DATE, TUNNEL_ID, COMPANY_ID, BLANK_NUMBER_INT)
Values
   ('2F1CF4BEF936544EE053930C1', '1', 'A', '0358900880', '3', 
    '1', TO_DATE('19.08.2015', 'DD.MM.YYYY'), TO_DATE('28.03.2016 16:34:36', 'DD.MM.YYYY HH24:MI:SS'), 0, 0, 
    '05', TO_DATE('28.03.2016 16:34:36', 'DD.MM.YYYY HH24:MI:SS'), '1', TO_DATE('19.08.2015', 'DD.MM.YYYY'), 0, 
    'bnta_20150114113243253_109.xml', TO_DATE('28.03.2016 15:48:55', 'DD.MM.YYYY HH24:MI:SS'), '2F1C55E5E9C84E01E053930C1', '03000000', 0);	
```
But, if change in Postgresql DDL MODULUS 262 to MODULUS 4 insert would by successfull!

**Comment by darold** [comment] 2018-08-24 09:52
I based the MODULUS value the the number of partitions associated with the table, obviously there is a problem in the list of partition associated to the table. I will use you example to try to reproduce.

**Comment by denoley** [comment] 2018-08-24 09:58
You can find subpartitions count in 
`select partition_name, subpartition_count from user/all_tab_partitions`

**Comment by darold** [comment] 2018-08-24 15:07
Commit 1a014f6 might solve this issue. Please use latest development code and let me now. This commit also include a fix on count of partitions that now include subpartition count.

**Comment by denoley** [comment] 2018-08-27 05:56
Partitions created and data loaded succefully!

**Comment by darold** [comment] 2018-08-27 08:41
Commit 503ed94 should add this behavior when PG_SUPPORTS_PARTITION is enable. Not yet tested but should do the work.

**Comment by denoley** [comment] 2018-08-27 11:59
Didn't work. Query executed on table at all (i.e. without partition/subpartition clause in the select statement).

**Comment by darold** [comment] 2018-09-04 22:29
Works at my side. I have a table BOOK1 with 3 partitions. When I export data I have the following:
```
ora2pg -c config/ora2pg.conf -t COPY -a 'BOOK.*' -b tmp/
[...]
[========================>] 0/0 rows (100.0%) Table BOOK1P1 (0 recs/sec)                         
[========================>] 0/0 rows (100.0%) Table BOOK1P2 (0 recs/sec)          
[========================>] 0/0 rows (100.0%) Table BOOK1P3 (0 recs/sec)          
```
Ora2Pg is extracting Oracle data from each partition. Here there is no rows but this is not a problem.

Then looking at files created during the export:
```
$ cat tmp/BOOK1P*

COPY book1 (id,c1) FROM STDIN;
\.

COPY book1 (id,c1) FROM STDIN;
\.

COPY book1 (id,c1) FROM STDIN;
\.
```
All data (if there was) will be imported into PostgreSQL using COPY into the main partitioned table `book1`.

Query used to export data from Oracle was:
```
SELECT "ID","C1" FROM "HR"."BOOK1" PARTITION(BOOK1P2) a;
SELECT "ID","C1" FROM "HR"."BOOK1" PARTITION(BOOK1P1) a;
SELECT "ID","C1" FROM "HR"."BOOK1" PARTITION(BOOK1P3) a;
```
perhaps I'm misunderstanding what you are explaining to me?

**Comment by denoley** [comment] 2018-09-06 10:02
Last 4 commits in master branch:
```
bash-4.2$ git pull
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 8 (delta 4), reused 8 (delta 4), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/darold/ora2pg
   548612d..5771e4c  master     -> origin/master
Updating 548612d..5771e4c
Fast-forward
 lib/Ora2Pg.pm | 24 +++++++++++++++++++-----
 1 file changed, 19 insertions(+), 5 deletions(-)

bash-4.2$ git log -4
commit 5771e4cd97a1ea01cfd31fc3ff0533c3fe356425
Author: Gilles Darold <gilles@darold.net>
Date:   Tue Sep 4 14:33:07 2018 +0200

    Fix unset oracle username when exporting DBLINK from database. Thanks to Denis Oleynikov for the report.

commit 8ae6244dd5ff9b60b87c0d148ce9ea78c2328e8e
Author: Gilles Darold <gilles@darold.net>
Date:   Tue Sep 4 12:53:44 2018 +0200

    Remove NO VALID to foreign keys on partitioned table. Thanks to Denis Oleynikov for the report.

commit 548612d55c3e4f0c3d788411dc54b28593720dd3
Author: Gilles Darold <gilles@darold.net>
Date:   Fri Aug 31 11:34:19 2018 +0200

    Fix crash of Ora2Pg on regexp with dynamic pattern base on package code.
    Thank to Alain Debie and  MikeCaliffCBORD for the report.

commit 503ed94402b55160145fdd91872fdfbd45e649f2
Author: Gilles Darold <gilles@darold.net>
Date:   Mon Aug 27 10:37:17 2018 +0200

    PostgreSQL native partitioning does not allow direct import of data into
    already attached partitions. When PG_SUPPORTS_PARTITION is enable we now
    force direct import into main single table but we keep Oracle export of
    data from individual partition. Previous behavior was to use main table
    from both side. Thanks to Denis Oleynikov for the report.
bash-4.2$
```

Is it there?

**Comment by darold** [comment] 2018-09-06 10:04
Yes, send me your ora2pg.conf file if it still doesn't works.

**Comment by denoley** [comment] 2018-09-06 13:08
Not working:
It generates:

```
SELECT  /*+ FULL(a) PARALLEL(a, 3) */
       "INFO_ID"...      
       "BLANK_NUMBER_INT"
  FROM "BSO_TEST2"."KBLN_INFO" a
```

[ora2pg.conf.txt](https://github.com/darold/ora2pg/files/2357139/ora2pg.conf.txt)

**Comment by denoley** [comment] 2018-09-06 14:19
so sad..

```
SELECT  /*+ FULL(a) PARALLEL(a, 3) */
       "INFO_ID",
[ora2pg.conf.txt](https://github.com/darold/ora2pg/files/2357419/ora2pg.conf.txt)

       "BLANK_TYPE_ID", ...
  FROM "BSO_TEST2"."KBLN_INFO" a
```

**Comment by darold** [comment] 2018-09-07 16:35
With last development code Ora2Pg now print the query send to Oracle in debug mode. Can you update to latest commits and give me the output of command:
```
ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf -d -q -a KBLN_INFO
```

**Comment by denoley** [comment] 2018-09-11 09:31
Output attached.

Ora2Pg info:
```
bash-4.2$ md5sum Ora2Pg.pm
0591539a50717e15ec473e04ab973222  Ora2Pg.pm
[log.txt](https://github.com/darold/ora2pg/files/2370402/log.txt)

bash-4.2$ git log -2
commit 6993e5d0364c91e55d903b85e2cc11dbdb56b95b
Merge: 2bbe179 8de4a30
Author: Gilles Darold <gilles@darold.net>
Date:   Mon Sep 10 08:43:01 2018 +0200

    Merge pull request #687 from Maxime2/keep-pkey-names

    Enforce KEEP_PKEY_NAMES=1 when USE_TABLESPACE is enabled

commit 8de4a30ad48d768b11f6d92469f7d4214a68cfd4
Author: Maxim Zakharov <dp.maxime@gmail.com>
Date:   Wed Sep 5 18:08:11 2018 +1000

    enforce KEEP_PKEY_NAMES when USE_TABLESPACE is enabled
```

It was opened only 1 session in Oracle with query:

```
SELECT  /*+ FULL(a) PARALLEL(a, 3) */
       "INFO_ID",
       "BLANK_TYPE_ID",
       "BLANK_SERIES",
       "BLANK_NUMBER",
       "CONTRACT_NUMBER",
       "ACC_SYSTEM_TYPE_ID",
       "ACC_STATUS_ID",
       "ACC_STATUS_CHANGE_DATE",
       "RECORD_DATE",
       "BLANK_VERSION",
       "REVOKE_REQUIRED",
       "BRANCH_ID",
       "PROCESS_STATUS_ID",
       "PROCESS_STATUS_CHANGE_DATE",
       "EXT_STATUS_ID",
       "EXT_STATUS_CHANGE_DATE",
       "SIGN_HISTORICAL_DATA",
       "TRANSITION_ID",
       "BASE_INFO_ID",
       "SEND_FILE_NAME",
       "SEND_FILE_DATE",
       "RESPONSE_FILE_NAME",
       "RESPONSE_FILE_DATE",
       "HEAD_BRANCH_ID",
       "TUNNEL_ID",
       "CONTRACT_ID",
       "FOR_UPDATE_AGGREGATE_TABLE",
       "COMPANY_ID",
       "BLANK_NUMBER_INT"
  FROM "BSO_TEST2"."KBLN_INFO" a
```

**Comment by darold** [comment] 2018-09-19 21:48
I'm not an Oracle expert, I don't know why there is just only one session on Oracle side, the parallelism  hint seems good. Perhaps this is not enough rows in this table and Oracle decide to not fork a parallel process.

**Closed** 2018-09-27 01:55 UTC
